use super::EmulatorConfigWriter;
use std::collections::HashMap;

pub struct DolphinConfigWriter;

impl DolphinConfigWriter {
    fn resolution_value(canonical: &str) -> &'static str {
        match canonical {
            "native" => "1", "2x" => "2", "3x" => "3", "4x" => "4",
            "5x" => "5", "6x" => "6", "8x" => "8", _ => "1",
        }
    }

    fn language_value(canonical: &str) -> &'static str {
        match canonical {
            "Japanese"   => "0",
            "English"    => "1",
            "German"     => "2",
            "French"     => "3",
            "Spanish"    => "4",
            "Italian"    => "5",
            "Korean"     => "8",
            "Chinese"    => "9",
            "Portuguese" => "1", // Dolphin doesn't have PT, fallback EN
            _ => "1",
        }
    }

    fn aspect_ratio_value(canonical: &str) -> &'static str {
        match canonical {
            "auto"    => "0",
            "16:9"    => "1",
            "4:3"     => "2",
            "stretch" => "3",
            _ => "0",
        }
    }

    fn bool_tf(canonical: &str) -> &'static str {
        if canonical == "true" { "True" } else { "False" }
    }
}

impl EmulatorConfigWriter for DolphinConfigWriter {
    fn emulator_name(&self) -> &str { "Dolphin" }
    fn config_format(&self) -> &str { "ini" }

    fn supported_settings(&self) -> Vec<&str> {
        vec![
            "internal_resolution", "fullscreen", "vsync", "aspect_ratio",
            "show_fps", "system_language",
        ]
    }

    fn default_config_path(&self) -> Option<String> {
        if let Some(docs) = dirs::document_dir() {
            let p = docs.join("Dolphin Emulator").join("Config").join("GFX.ini");
            if p.exists() { return Some(p.to_string_lossy().to_string()); }
        }
        None
    }

    fn preview_config(&self, settings: &HashMap<String, String>) -> String {
        let mut lines = Vec::new();
        lines.push("; Dolphin GFX config — generated by Cubi Frontend".to_string());
        lines.push(format!("; Generated: {}", chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")));
        lines.push(String::new());

        // GFX.ini sections
        lines.push("[Settings]".to_string());
        if let Some(v) = settings.get("internal_resolution") {
            lines.push(format!("InternalResolution = {}", Self::resolution_value(v)));
        }
        if let Some(v) = settings.get("aspect_ratio") {
            lines.push(format!("AspectRatio = {}", Self::aspect_ratio_value(v)));
        }
        if let Some(v) = settings.get("show_fps") {
            lines.push(format!("ShowFPS = {}", Self::bool_tf(v)));
        }
        lines.push(String::new());

        lines.push("[Hardware]".to_string());
        lines.push("VSync = False".to_string()); // Always off
        lines.push(String::new());

        lines.push("[Display]".to_string());
        if let Some(v) = settings.get("fullscreen") {
            lines.push(format!("Fullscreen = {}", Self::bool_tf(v)));
        }
        lines.push(String::new());

        // Dolphin.ini language
        lines.push("; -- Dolphin.ini settings --".to_string());
        lines.push("[Core]".to_string());
        if let Some(v) = settings.get("system_language") {
            lines.push(format!("SelectedLanguage = {}", Self::language_value(v)));
        }
        lines.push(String::new());
        lines.join("\n")
    }
}
