use super::EmulatorConfigWriter;
use std::collections::HashMap;

pub struct DuckStationConfigWriter;

impl DuckStationConfigWriter {
    fn resolution_value(canonical: &str) -> &'static str {
        match canonical {
            "native" => "1", "2x" => "2", "3x" => "3", "4x" => "4",
            "5x" => "5", "6x" => "6", "8x" => "8", _ => "1",
        }
    }

    fn bool_lower(canonical: &str) -> &'static str {
        if canonical == "true" { "true" } else { "false" }
    }

    fn aspect_ratio_value(canonical: &str) -> &'static str {
        match canonical {
            "auto"    => "Auto",
            "4:3"     => "4:3",
            "16:9"    => "16:9",
            "stretch" => "Stretch",
            _ => "Auto",
        }
    }

    /// DuckStation doesn't have per-language settings; it uses region instead.
    fn region_value(canonical: &str) -> &'static str {
        match canonical {
            "Japanese" => "NTSC-J",
            "English"  => "NTSC-U",
            "French" | "German" | "Italian" | "Spanish" | "Portuguese" => "PAL",
            "Chinese" | "Korean" => "NTSC-J",
            _ => "NTSC-U",
        }
    }
}

impl EmulatorConfigWriter for DuckStationConfigWriter {
    fn emulator_name(&self) -> &str { "DuckStation" }
    fn config_format(&self) -> &str { "ini" }

    fn supported_settings(&self) -> Vec<&str> {
        vec![
            "internal_resolution", "fullscreen", "vsync", "aspect_ratio",
            "show_fps", "system_language", "audio_volume",
        ]
    }

    fn default_config_path(&self) -> Option<String> {
        if let Some(docs) = dirs::document_dir() {
            let p = docs.join("DuckStation").join("settings.ini");
            if p.exists() { return Some(p.to_string_lossy().to_string()); }
        }
        None
    }

    fn preview_config(&self, settings: &HashMap<String, String>) -> String {
        let mut lines = Vec::new();
        lines.push("; DuckStation general settings — generated by Cubi Frontend".to_string());
        lines.push(format!("; Generated: {}", chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")));
        lines.push(String::new());

        lines.push("[GPU]".to_string());
        if let Some(v) = settings.get("internal_resolution") {
            lines.push(format!("ResolutionScale = {}", Self::resolution_value(v)));
        }
        lines.push(String::new());

        lines.push("[Display]".to_string());
        lines.push("VSync = false".to_string()); // Always off
        if let Some(v) = settings.get("aspect_ratio") {
            lines.push(format!("AspectRatio = {}", Self::aspect_ratio_value(v)));
        }
        if let Some(v) = settings.get("show_fps") {
            lines.push(format!("ShowFPS = {}", Self::bool_lower(v)));
        }
        lines.push(String::new());

        lines.push("[Main]".to_string());
        if let Some(v) = settings.get("fullscreen") {
            lines.push(format!("StartFullscreen = {}", Self::bool_lower(v)));
        }
        lines.push(String::new());

        lines.push("[Console]".to_string());
        if let Some(v) = settings.get("system_language") {
            lines.push(format!("Region = {}", Self::region_value(v)));
        }
        lines.push(String::new());

        if let Some(v) = settings.get("audio_volume") {
            lines.push("[Audio]".to_string());
            lines.push(format!("OutputVolume = {}", v));
            lines.push(String::new());
        }

        lines.join("\n")
    }
}
