use super::EmulatorConfigWriter;
use std::collections::HashMap;

pub struct Pcsx2ConfigWriter;

impl Pcsx2ConfigWriter {
    fn resolution_value(canonical: &str) -> &'static str {
        match canonical {
            "native" => "1", "2x" => "2", "3x" => "3", "4x" => "4",
            "5x" => "5", "6x" => "6", "8x" => "8", _ => "1",
        }
    }

    fn language_value(canonical: &str) -> &'static str {
        match canonical {
            "Japanese"   => "0",
            "English"    => "1",
            "French"     => "2",
            "Spanish"    => "3",
            "German"     => "4",
            "Italian"    => "5",
            "Portuguese" => "6",
            "Chinese"    => "7",  // Simplified
            "Korean"     => "1",  // PCSX2 doesn't have KO natively, fallback EN
            _ => "1",
        }
    }

    fn aspect_ratio_value(canonical: &str) -> &'static str {
        match canonical {
            "auto"    => "Auto:0",
            "4:3"     => "4:3:1",
            "16:9"    => "16:9:2",
            "stretch" => "Stretch:3",
            _ => "Auto:0",
        }
    }

    fn bool_lower(canonical: &str) -> &'static str {
        if canonical == "true" { "true" } else { "false" }
    }
}

impl EmulatorConfigWriter for Pcsx2ConfigWriter {
    fn emulator_name(&self) -> &str { "PCSX2" }
    fn config_format(&self) -> &str { "ini" }

    fn supported_settings(&self) -> Vec<&str> {
        vec![
            "internal_resolution", "fullscreen", "vsync", "aspect_ratio",
            "show_fps", "system_language", "audio_volume",
        ]
    }

    fn default_config_path(&self) -> Option<String> {
        if let Some(docs) = dirs::document_dir() {
            let p = docs.join("PCSX2").join("inis").join("PCSX2.ini");
            if p.exists() { return Some(p.to_string_lossy().to_string()); }
        }
        None
    }

    fn preview_config(&self, settings: &HashMap<String, String>) -> String {
        let mut lines = Vec::new();
        lines.push("; PCSX2 general settings — generated by Cubi Frontend".to_string());
        lines.push(format!("; Generated: {}", chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")));
        lines.push(String::new());

        lines.push("[EmuCore/GS]".to_string());
        if let Some(v) = settings.get("internal_resolution") {
            lines.push(format!("upscale_multiplier = {}", Self::resolution_value(v)));
        }
        // V-Sync always off
        lines.push("VsyncEnable = 0".to_string());
        if let Some(v) = settings.get("aspect_ratio") {
            lines.push(format!("AspectRatio = {}", Self::aspect_ratio_value(v)));
        }
        if let Some(v) = settings.get("show_fps") {
            lines.push(format!("OsdShowFPS = {}", Self::bool_lower(v)));
        }
        lines.push(String::new());

        lines.push("[UI]".to_string());
        if let Some(v) = settings.get("fullscreen") {
            lines.push(format!("StartFullscreen = {}", Self::bool_lower(v)));
        }
        lines.push(String::new());

        lines.push("[EmuCore]".to_string());
        if let Some(v) = settings.get("system_language") {
            lines.push(format!("LanguageId = {}", Self::language_value(v)));
        }
        lines.push(String::new());

        if let Some(v) = settings.get("audio_volume") {
            lines.push("[SPU2/Mixing]".to_string());
            lines.push(format!("FinalVolume = {}", v));
            lines.push(String::new());
        }

        lines.join("\n")
    }
}
