use super::EmulatorConfigWriter;
use std::collections::HashMap;

pub struct PpssppConfigWriter;

impl PpssppConfigWriter {
    fn resolution_value(canonical: &str) -> &'static str {
        match canonical {
            "native" => "1", "2x" => "2", "3x" => "3", "4x" => "4",
            "5x" => "5", "6x" => "6", "8x" => "8", _ => "1",
        }
    }

    fn language_value(canonical: &str) -> &'static str {
        match canonical {
            "Japanese"   => "0",
            "English"    => "1",
            "French"     => "3",
            "Spanish"    => "4",
            "German"     => "5",
            "Italian"    => "6",
            "Portuguese" => "8",
            "Korean"     => "9",
            "Chinese"    => "11", // Simplified
            _ => "1",
        }
    }

    fn bool_tf(canonical: &str) -> &'static str {
        if canonical == "true" { "True" } else { "False" }
    }

    fn texture_filtering_value(canonical: &str) -> &'static str {
        match canonical {
            "nearest" => "2",
            "linear"  => "3",
            _ => "1", // auto
        }
    }
}

impl EmulatorConfigWriter for PpssppConfigWriter {
    fn emulator_name(&self) -> &str { "PPSSPP" }
    fn config_format(&self) -> &str { "ini" }

    fn supported_settings(&self) -> Vec<&str> {
        vec![
            "internal_resolution", "fullscreen", "vsync",
            "system_language", "texture_filtering", "show_fps",
        ]
    }

    fn default_config_path(&self) -> Option<String> {
        if let Some(docs) = dirs::document_dir() {
            let p = docs.join("PPSSPP").join("memstick").join("PSP").join("SYSTEM").join("ppsspp.ini");
            if p.exists() { return Some(p.to_string_lossy().to_string()); }
        }
        None
    }

    fn preview_config(&self, settings: &HashMap<String, String>) -> String {
        let mut lines = Vec::new();
        lines.push("; PPSSPP general settings — generated by Cubi Frontend".to_string());
        lines.push(format!("; Generated: {}", chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")));
        lines.push(String::new());

        lines.push("[Graphics]".to_string());
        if let Some(v) = settings.get("internal_resolution") {
            lines.push(format!("InternalResolution = {}", Self::resolution_value(v)));
        }
        if let Some(v) = settings.get("fullscreen") {
            lines.push(format!("FullScreen = {}", Self::bool_tf(v)));
        }
        lines.push("VSync = False".to_string()); // Always off
        if let Some(v) = settings.get("texture_filtering") {
            lines.push(format!("TextureFiltering = {}", Self::texture_filtering_value(v)));
        }
        if let Some(v) = settings.get("show_fps") {
            let counter = if v == "true" { "3" } else { "0" };
            lines.push(format!("ShowFPSCounter = {}", counter));
        }
        lines.push(String::new());

        lines.push("[SystemParam]".to_string());
        if let Some(v) = settings.get("system_language") {
            lines.push(format!("PSPSystemLanguage = {}", Self::language_value(v)));
        }
        lines.push(String::new());
        lines.join("\n")
    }
}
