use super::EmulatorConfigWriter;
use std::collections::HashMap;

pub struct RetroArchConfigWriter;

impl RetroArchConfigWriter {
    fn resolution_value(canonical: &str) -> &'static str {
        match canonical {
            "native" => "1",
            "2x" => "2",
            "3x" => "3",
            "4x" => "4",
            "5x" => "5",
            "6x" => "6",
            "8x" => "8",
            _ => "1",
        }
    }

    fn language_value(canonical: &str) -> &'static str {
        match canonical {
            "English"    => "0",
            "Japanese"   => "2",
            "Spanish"    => "4",
            "French"     => "5",
            "German"     => "6",
            "Italian"    => "7",
            "Portuguese" => "16",
            "Chinese"    => "3",
            "Korean"     => "10",
            _ => "0",
        }
    }

    fn aspect_ratio_value(canonical: &str) -> &'static str {
        match canonical {
            "auto"    => "22",
            "4:3"     => "21",
            "16:9"    => "20",
            "stretch" => "23",
            _ => "22",
        }
    }

    fn bool_str(canonical: &str) -> &'static str {
        match canonical {
            "true" => "true",
            _ => "false",
        }
    }

    /// Convert 0-100 percentage to RetroArch dB value.
    /// RA uses dB where 0.0 = max, negative = quieter.
    /// Simple mapping: 100→0.0, 75→-3.0, 50→-6.0, 25→-12.0, 0→-80.0
    fn volume_db(pct: &str) -> String {
        let v: f64 = pct.parse().unwrap_or(100.0);
        if v <= 0.0 {
            "-80.0".to_string()
        } else if v >= 100.0 {
            "0.0".to_string()
        } else {
            format!("{:.1}", 20.0 * (v / 100.0).log10())
        }
    }

    fn frame_limit_value(canonical: &str) -> &'static str {
        match canonical {
            "auto"      => "0.0",
            "30"        => "30.0",
            "60"        => "60.0",
            "120"       => "120.0",
            "unlimited" => "0.0",
            _ => "0.0",
        }
    }

    fn fast_forward_value(canonical: &str) -> &'static str {
        match canonical {
            "2x"        => "2.0",
            "3x"        => "3.0",
            "4x"        => "4.0",
            "unlimited" => "0.0",
            _ => "2.0",
        }
    }
}

impl EmulatorConfigWriter for RetroArchConfigWriter {
    fn emulator_name(&self) -> &str { "RetroArch" }
    fn config_format(&self) -> &str { "cfg" }

    fn supported_settings(&self) -> Vec<&str> {
        vec![
            "internal_resolution", "fullscreen", "vsync", "aspect_ratio",
            "show_fps", "system_language", "audio_volume", "frame_limit",
            "fast_forward_speed", "texture_filtering",
        ]
    }

    fn default_config_path(&self) -> Option<String> {
        if let Some(appdata) = std::env::var_os("APPDATA") {
            let p = std::path::Path::new(&appdata).join("RetroArch").join("retroarch.cfg");
            if p.exists() { return Some(p.to_string_lossy().to_string()); }
        }
        None
    }

    fn preview_config(&self, settings: &HashMap<String, String>) -> String {
        let mut lines = Vec::new();
        lines.push("# RetroArch general settings — generated by Cubi Frontend".to_string());
        lines.push(format!("# Generated: {}", chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")));
        lines.push(String::new());

        if let Some(v) = settings.get("internal_resolution") {
            lines.push(format!("video_scale = \"{}\"", Self::resolution_value(v)));
        }
        if let Some(v) = settings.get("fullscreen") {
            lines.push(format!("video_fullscreen = \"{}\"", Self::bool_str(v)));
        }
        // V-Sync always false
        lines.push("video_vsync = \"false\"".to_string());
        if let Some(v) = settings.get("aspect_ratio") {
            lines.push(format!("aspect_ratio_index = \"{}\"", Self::aspect_ratio_value(v)));
        }
        if let Some(v) = settings.get("show_fps") {
            lines.push(format!("fps_show = \"{}\"", Self::bool_str(v)));
        }
        if let Some(v) = settings.get("system_language") {
            lines.push(format!("user_language = \"{}\"", Self::language_value(v)));
        }
        if let Some(v) = settings.get("audio_volume") {
            lines.push(format!("audio_volume = \"{}\"", Self::volume_db(v)));
        }
        if let Some(v) = settings.get("frame_limit") {
            lines.push(format!("fastforward_ratio = \"{}\"", Self::frame_limit_value(v)));
        }
        if let Some(v) = settings.get("fast_forward_speed") {
            lines.push(format!("fastforward_ratio = \"{}\"", Self::fast_forward_value(v)));
        }
        if let Some(v) = settings.get("texture_filtering") {
            let smooth = if v == "linear" { "true" } else { "false" };
            lines.push(format!("video_smooth = \"{}\"", smooth));
        }
        lines.push(String::new());
        lines.join("\n")
    }
}
