use super::EmulatorConfigWriter;
use std::collections::HashMap;

pub struct Rpcs3ConfigWriter;

impl Rpcs3ConfigWriter {
    fn resolution_value(canonical: &str) -> &'static str {
        match canonical {
            "native" | "2x" => "1280x720",
            "3x" => "1920x1080",
            "4x" | "5x" | "6x" | "8x" => "3840x2160",
            _ => "1280x720",
        }
    }

    fn frame_limit_value(canonical: &str) -> &'static str {
        match canonical {
            "auto"      => "Auto",
            "30"        => "30",
            "60"        => "60",
            "120"       => "Off",  // RPCS3 max is typically 60, unlimited → Off
            "unlimited" => "Off",
            _ => "Auto",
        }
    }
}

impl EmulatorConfigWriter for Rpcs3ConfigWriter {
    fn emulator_name(&self) -> &str { "RPCS3" }
    fn config_format(&self) -> &str { "yml" }

    fn supported_settings(&self) -> Vec<&str> {
        vec!["internal_resolution", "fullscreen", "vsync", "frame_limit"]
    }

    fn default_config_path(&self) -> Option<String> {
        if let Some(appdata) = std::env::var_os("APPDATA") {
            let p = std::path::Path::new(&appdata).join("rpcs3").join("config.yml");
            if p.exists() { return Some(p.to_string_lossy().to_string()); }
        }
        None
    }

    fn preview_config(&self, settings: &HashMap<String, String>) -> String {
        let mut lines = Vec::new();
        lines.push("# RPCS3 general settings — generated by Cubi Frontend".to_string());
        lines.push(format!("# Generated: {}", chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")));
        lines.push(String::new());

        lines.push("Video:".to_string());
        if let Some(v) = settings.get("internal_resolution") {
            lines.push(format!("  Resolution: {}", Self::resolution_value(v)));
        }
        lines.push("  VSync: false".to_string()); // Always off
        if let Some(v) = settings.get("frame_limit") {
            lines.push(format!("  Frame limit: {}", Self::frame_limit_value(v)));
        }
        lines.push(String::new());

        lines.push("Miscellaneous:".to_string());
        if let Some(v) = settings.get("fullscreen") {
            let val = if v == "true" { "true" } else { "false" };
            lines.push(format!("  Start games in fullscreen mode: {}", val));
        }
        lines.push(String::new());
        lines.join("\n")
    }
}
