use super::EmulatorConfigWriter;
use std::collections::HashMap;

pub struct RyujinxConfigWriter;

impl RyujinxConfigWriter {
    fn resolution_value(canonical: &str) -> &'static str {
        match canonical {
            "native" => "1", "2x" => "2", "3x" => "3",
            "4x" | "5x" | "6x" | "8x" => "4", // Ryujinx max ~4x
            _ => "1",
        }
    }

    fn language_value(canonical: &str) -> &'static str {
        match canonical {
            "Japanese"   => "Japanese",
            "English"    => "AmericanEnglish",
            "French"     => "French",
            "German"     => "German",
            "Spanish"    => "Spanish",
            "Italian"    => "Italian",
            "Portuguese" => "BrazilianPortuguese",
            "Chinese"    => "SimplifiedChinese",
            "Korean"     => "Korean",
            _ => "AmericanEnglish",
        }
    }
}

impl EmulatorConfigWriter for RyujinxConfigWriter {
    fn emulator_name(&self) -> &str { "Ryujinx" }
    fn config_format(&self) -> &str { "json" }

    fn supported_settings(&self) -> Vec<&str> {
        vec![
            "internal_resolution", "fullscreen", "vsync",
            "system_language", "audio_volume",
        ]
    }

    fn default_config_path(&self) -> Option<String> {
        if let Some(appdata) = std::env::var_os("APPDATA") {
            let p = std::path::Path::new(&appdata).join("Ryujinx").join("Config.json");
            if p.exists() { return Some(p.to_string_lossy().to_string()); }
        }
        None
    }

    fn preview_config(&self, settings: &HashMap<String, String>) -> String {
        let mut lines = Vec::new();
        lines.push("// Ryujinx general settings — generated by Cubi Frontend".to_string());
        lines.push(format!("// Generated: {}", chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")));
        lines.push("{".to_string());

        let mut entries: Vec<String> = Vec::new();

        if let Some(v) = settings.get("internal_resolution") {
            entries.push(format!("  \"res_scale\": {}", Self::resolution_value(v)));
        }
        if let Some(v) = settings.get("fullscreen") {
            let val = if v == "true" { "true" } else { "false" };
            entries.push(format!("  \"start_fullscreen\": {}", val));
        }
        // V-Sync always off
        entries.push("  \"enable_vsync\": false".to_string());
        if let Some(v) = settings.get("system_language") {
            entries.push(format!("  \"system_language\": \"{}\"", Self::language_value(v)));
        }
        if let Some(v) = settings.get("audio_volume") {
            let vol: f64 = v.parse().unwrap_or(100.0) / 100.0;
            entries.push(format!("  \"audio_volume\": {:.2}", vol));
        }

        lines.push(entries.join(",\n"));
        lines.push("}".to_string());
        lines.push(String::new());
        lines.join("\n")
    }
}
