use super::EmulatorConfigWriter;
use std::collections::HashMap;

/// Ryujinx Nintendo Switch emulator configuration writer.
/// 
/// PERFORMANCE TIPS:
/// - Enable PTC (Profiled Persistent Translation Cache) for faster loading after first run
/// - Enable shader cache to reduce stuttering
/// - Use Vulkan backend for better performance (if GPU supports it)
/// - Enable backend multithreading for multi-core CPUs (CRITICAL)
/// - Disable V-Sync if experiencing slowdown (use frame limiting instead)
/// - Use Docked mode for better performance (higher clocks)
/// - Enable Macro HLE (High Level Emulation) for better GPU performance
/// - Disable texture recompression to trade VRAM for speed
/// - Use HostMapped memory manager (or HostMappedUnsafe for maximum speed)
/// - Enable Expand RAM for demanding games
/// - Lower internal resolution if performance is poor (native = 1x)
/// - Enable "Ignore Missing Services" for better compatibility
/// 
/// If games run slower than real-time but audio is fine:
/// - Check CPU usage - Ryujinx is CPU-intensive
/// - Ensure PTC and shader cache are enabled
/// - Ensure backend multithreading is enabled (most important!)
/// - Try lowering resolution scale to 1x (native)
/// - Make sure Macro HLE is enabled
/// - Switch to HostMapped or HostMappedUnsafe memory mode
/// - Close other applications consuming CPU
pub struct RyujinxConfigWriter;

impl RyujinxConfigWriter {
    fn resolution_value(canonical: &str) -> &'static str {
        match canonical {
            "native" => "1", "2x" => "2", "3x" => "3",
            "4x" | "5x" | "6x" | "8x" => "4", // Ryujinx max ~4x
            _ => "1",
        }
    }

    fn language_value(canonical: &str) -> &'static str {
        match canonical {
            "Japanese"   => "Japanese",
            "English"    => "AmericanEnglish",
            "French"     => "French",
            "German"     => "German",
            "Spanish"    => "Spanish",
            "Italian"    => "Italian",
            "Portuguese" => "BrazilianPortuguese",
            "Chinese"    => "SimplifiedChinese",
            "Korean"     => "Korean",
            _ => "AmericanEnglish",
        }
    }
}

impl EmulatorConfigWriter for RyujinxConfigWriter {
    fn emulator_name(&self) -> &str { "Ryujinx" }
    fn config_format(&self) -> &str { "json" }

    fn supported_settings(&self) -> Vec<&str> {
        vec![
            "internal_resolution", "fullscreen", "vsync",
            "system_language", "audio_volume",
            "renderer", "docked_mode", "enable_ptc",
            "enable_shader_cache", "backend_threading",
            "expand_ram", "ignore_missing_services",
            "aspect_ratio", "memory_manager_mode",
            "enable_macro_hle", "enable_texture_recompression",
        ]
    }

    fn default_config_path(&self) -> Option<String> {
        if let Some(appdata) = std::env::var_os("APPDATA") {
            let p = std::path::Path::new(&appdata).join("Ryujinx").join("Config.json");
            if p.exists() { return Some(p.to_string_lossy().to_string()); }
        }
        None
    }

    fn preview_config(&self, settings: &HashMap<String, String>) -> String {
        let mut lines = Vec::new();
        lines.push("// Ryujinx general settings — generated by Cubi Frontend".to_string());
        lines.push(format!("// Generated: {}", chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")));
        lines.push("// PERFORMANCE OPTIMIZATIONS ENABLED FOR BEST SPEED".to_string());
        lines.push("{".to_string());

        let mut entries: Vec<String> = Vec::new();

        // Graphics settings
        if let Some(v) = settings.get("internal_resolution") {
            entries.push(format!("  \"res_scale\": {}", Self::resolution_value(v)));
        }
        if let Some(v) = settings.get("fullscreen") {
            let val = if v == "true" { "true" } else { "false" };
            entries.push(format!("  \"start_fullscreen\": {}", val));
        }

        // V-Sync - respect user setting
        if let Some(v) = settings.get("vsync") {
            let val = if v == "true" { "true" } else { "false" };
            entries.push(format!("  \"enable_vsync\": {}", val));
        } else {
            entries.push("  \"enable_vsync\": false".to_string());
        }

        // Graphics backend (Vulkan is faster than OpenGL in most cases)
        // Check both "renderer" (canonical) and "graphics_backend" (legacy)
        let graphics = settings.get("renderer").or_else(|| settings.get("graphics_backend"));
        if let Some(v) = graphics {
            let backend = match v.as_str() {
                "vulkan" => "Vulkan",
                "opengl" => "OpenGL",
                _ => "Vulkan",
            };
            entries.push(format!("  \"graphics_backend\": \"{}\"", backend));
        } else {
            entries.push("  \"graphics_backend\": \"Vulkan\"".to_string());
        }

        // Backend multithreading (CRITICAL for performance)
        if let Some(v) = settings.get("backend_threading") {
            let val = if v == "false" { "false" } else { "true" };
            entries.push(format!("  \"backend_threading\": {}", val));
        } else {
            entries.push("  \"backend_threading\": true".to_string());
        }

        // PTC (Profiled Persistent Translation Cache) - speeds up subsequent launches
        if let Some(v) = settings.get("enable_ptc") {
            let val = if v == "false" { "false" } else { "true" };
            entries.push(format!("  \"enable_ptc\": {}", val));
        } else {
            entries.push("  \"enable_ptc\": true".to_string());
        }

        // Shader cache (reduces stuttering)
        if let Some(v) = settings.get("enable_shader_cache") {
            let val = if v == "false" { "false" } else { "true" };
            entries.push(format!("  \"enable_shader_cache\": {}", val));
        } else {
            entries.push("  \"enable_shader_cache\": true".to_string());
        }

        // Docked mode (higher performance/resolution vs handheld)
        if let Some(v) = settings.get("docked_mode") {
            let val = if v == "false" { "false" } else { "true" };
            entries.push(format!("  \"docked_mode\": {}", val));
        } else {
            entries.push("  \"docked_mode\": true".to_string());
        }

        // Expand RAM to 8GB (some games need it, enabled by default for performance)
        if let Some(v) = settings.get("expand_ram") {
            let val = if v == "false" { "false" } else { "true" };
            entries.push(format!("  \"expand_ram\": {}", val));
        } else {
            entries.push("  \"expand_ram\": true".to_string());
        }

        // Ignore missing services (helps with compatibility)
        if let Some(v) = settings.get("ignore_missing_services") {
            let val = if v == "false" { "false" } else { "true" };
            entries.push(format!("  \"ignore_missing_services\": {}", val));
        } else {
            entries.push("  \"ignore_missing_services\": true".to_string());
        }

        // Aspect ratio
        if let Some(v) = settings.get("aspect_ratio") {
            let ratio = match v.as_str() {
                "16:9" => "Fixed16x9",
                "16:10" => "Fixed16x10",
                "21:9" => "Fixed21x9",
                "4:3" => "Fixed4x3",
                _ => "Fixed16x9",
            };
            entries.push(format!("  \"aspect_ratio\": \"{}\"", ratio));
        }

        // Memory manager mode (HostMappedUnsafe is fastest but less compatible)
        if let Some(v) = settings.get("memory_manager_mode") {
            let mode = match v.as_str() {
                "software" => "Software",
                "host" => "HostMapped",
                "host_unsafe" => "HostMappedUnsafe",
                _ => "HostMapped",
            };
            entries.push(format!("  \"memory_manager_mode\": \"{}\"", mode));
        } else {
            entries.push("  \"memory_manager_mode\": \"HostMapped\"".to_string());
        }

        // Macro HLE (High Level Emulation) - improves performance
        if let Some(v) = settings.get("enable_macro_hle") {
            let val = if v == "false" { "false" } else { "true" };
            entries.push(format!("  \"enable_macro_hle\": {}", val));
        } else {
            entries.push("  \"enable_macro_hle\": true".to_string());
        }

        // Texture recompression (disabling improves performance at cost of VRAM)
        if let Some(v) = settings.get("enable_texture_recompression") {
            let val = if v == "true" { "true" } else { "false" };
            entries.push(format!("  \"enable_texture_recompression\": {}", val));
        } else {
            entries.push("  \"enable_texture_recompression\": false".to_string());
        }

        // System settings
        if let Some(v) = settings.get("system_language") {
            entries.push(format!("  \"system_language\": \"{}\"", Self::language_value(v)));
        }
        if let Some(v) = settings.get("audio_volume") {
            let vol: f64 = v.parse().unwrap_or(100.0) / 100.0;
            entries.push(format!("  \"audio_volume\": {:.2}", vol.clamp(0.0, 1.0)));
        }

        lines.push(entries.join(",\n"));
        lines.push("}".to_string());
        lines.push(String::new());
        lines.join("\n")
    }
}
