use super::EmulatorConfigWriter;
use std::collections::HashMap;

pub struct XemuConfigWriter;

impl XemuConfigWriter {
    fn resolution_value(canonical: &str) -> &'static str {
        match canonical {
            "native" => "1", "2x" => "2", "3x" => "3",
            "4x" | "5x" | "6x" | "8x" => "4", // xemu max 4x
            _ => "1",
        }
    }
}

impl EmulatorConfigWriter for XemuConfigWriter {
    fn emulator_name(&self) -> &str { "xemu" }
    fn config_format(&self) -> &str { "toml" }

    fn supported_settings(&self) -> Vec<&str> {
        vec!["internal_resolution", "fullscreen", "vsync"]
    }

    fn default_config_path(&self) -> Option<String> {
        if let Some(appdata) = std::env::var_os("LOCALAPPDATA") {
            let p = std::path::Path::new(&appdata).join("xemu").join("xemu.toml");
            if p.exists() { return Some(p.to_string_lossy().to_string()); }
        }
        None
    }

    fn preview_config(&self, settings: &HashMap<String, String>) -> String {
        let mut lines = Vec::new();
        lines.push("# xemu general settings — generated by Cubi Frontend".to_string());
        lines.push(format!("# Generated: {}", chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")));
        lines.push(String::new());

        lines.push("[display]".to_string());
        if let Some(v) = settings.get("internal_resolution") {
            lines.push(format!("render_scale = {}", Self::resolution_value(v)));
        }
        if let Some(v) = settings.get("fullscreen") {
            let val = if v == "true" { "true" } else { "false" };
            lines.push(format!("fullscreen = {}", val));
        }
        lines.push("vsync = false".to_string()); // Always off
        lines.push(String::new());
        lines.join("\n")
    }
}
