use super::EmulatorExporter;
use crate::models::ButtonBinding;

pub struct DolphinExporter;

impl DolphinExporter {
    fn dolphin_key(action: &str) -> Option<&'static str> {
        match action {
            "game_a"           => Some("Buttons/A"),
            "game_b"           => Some("Buttons/B"),
            "game_x"           => Some("Buttons/X"),
            "game_y"           => Some("Buttons/Y"),
            "game_l1"          => Some("Triggers/L"),
            "game_r1"          => Some("Triggers/R"),
            "game_l2"          => Some("Triggers/L-Analog"),
            "game_r2"          => Some("Triggers/R-Analog"),
            "game_start"       => Some("Buttons/Start"),
            "game_dpad_up"     => Some("D-Pad/Up"),
            "game_dpad_down"   => Some("D-Pad/Down"),
            "game_dpad_left"   => Some("D-Pad/Left"),
            "game_dpad_right"  => Some("D-Pad/Right"),
            _ => None,
        }
    }
}

impl EmulatorExporter for DolphinExporter {
    fn emulator_name(&self) -> &str { "Dolphin" }
    fn file_extension(&self) -> &str { "ini" }

    fn export(&self, bindings: &[ButtonBinding]) -> String {
        let mut lines = Vec::new();
        lines.push("; Dolphin GCPad config — generated by Cubi Frontend".to_string());
        lines.push(format!("; Generated: {}", chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")));
        lines.push(String::new());
        lines.push("[GCPad1]".to_string());
        lines.push("Device = SDL/0/Gamepad".to_string());
        lines.push(String::new());

        for b in bindings {
            if b.button_index < 0 { continue; }
            if let Some(key) = Self::dolphin_key(&b.action) {
                lines.push(format!("{} = `Button {}`", key, b.button_index));
            }
        }
        lines.push(String::new());
        lines.join("\n")
    }
}
