use super::EmulatorExporter;
use crate::models::ButtonBinding;

pub struct DuckStationExporter;

impl DuckStationExporter {
    fn ds_key(action: &str) -> Option<&'static str> {
        match action {
            "game_a"           => Some("Pad1/Cross"),
            "game_b"           => Some("Pad1/Circle"),
            "game_x"           => Some("Pad1/Square"),
            "game_y"           => Some("Pad1/Triangle"),
            "game_l1"          => Some("Pad1/L1"),
            "game_r1"          => Some("Pad1/R1"),
            "game_l2"          => Some("Pad1/L2"),
            "game_r2"          => Some("Pad1/R2"),
            "game_start"       => Some("Pad1/Start"),
            "game_select"      => Some("Pad1/Select"),
            "game_dpad_up"     => Some("Pad1/Up"),
            "game_dpad_down"   => Some("Pad1/Down"),
            "game_dpad_left"   => Some("Pad1/Left"),
            "game_dpad_right"  => Some("Pad1/Right"),
            _ => None,
        }
    }
}

impl EmulatorExporter for DuckStationExporter {
    fn emulator_name(&self) -> &str { "DuckStation" }
    fn file_extension(&self) -> &str { "ini" }

    fn export(&self, bindings: &[ButtonBinding]) -> String {
        let mut lines = Vec::new();
        lines.push("; DuckStation controller config — generated by Cubi Frontend".to_string());
        lines.push(format!("; Generated: {}", chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")));
        lines.push(String::new());
        lines.push("[Controller1]".to_string());
        lines.push("Type = DigitalController".to_string());
        lines.push(String::new());

        for b in bindings {
            if b.button_index < 0 { continue; }
            if let Some(key) = Self::ds_key(&b.action) {
                lines.push(format!("{} = SDL-0/Button{}", key, b.button_index));
            }
        }
        lines.push(String::new());
        lines.join("\n")
    }
}
