use super::EmulatorExporter;
use crate::models::ButtonBinding;

pub struct RetroArchExporter;

impl RetroArchExporter {
    /// Map our canonical action names → RetroArch config key names.
    fn ra_key(action: &str) -> Option<&'static str> {
        match action {
            // Game buttons
            "game_a"           => Some("input_player1_b_btn"),       // RA: B = south face
            "game_b"           => Some("input_player1_a_btn"),       // RA: A = east face
            "game_x"           => Some("input_player1_y_btn"),       // RA: Y = west face
            "game_y"           => Some("input_player1_x_btn"),       // RA: X = north face
            "game_l1"          => Some("input_player1_l_btn"),
            "game_r1"          => Some("input_player1_r_btn"),
            "game_l2"          => Some("input_player1_l2_btn"),
            "game_r2"          => Some("input_player1_r2_btn"),
            "game_l3"          => Some("input_player1_l3_btn"),
            "game_r3"          => Some("input_player1_r3_btn"),
            "game_start"       => Some("input_player1_start_btn"),
            "game_select"      => Some("input_player1_select_btn"),
            "game_dpad_up"     => Some("input_player1_up_btn"),
            "game_dpad_down"   => Some("input_player1_down_btn"),
            "game_dpad_left"   => Some("input_player1_left_btn"),
            "game_dpad_right"  => Some("input_player1_right_btn"),
            // Hotkeys
            "hotkey_menu"         => Some("input_enable_hotkey_btn"),
            "hotkey_save_state"   => Some("input_save_state_btn"),
            "hotkey_load_state"   => Some("input_load_state_btn"),
            "hotkey_fast_forward" => Some("input_toggle_fast_forward_btn"),
            "hotkey_screenshot"   => Some("input_screenshot_btn"),
            _ => None,
        }
    }
}

impl EmulatorExporter for RetroArchExporter {
    fn emulator_name(&self) -> &str { "RetroArch" }
    fn file_extension(&self) -> &str { "cfg" }

    fn export(&self, bindings: &[ButtonBinding]) -> String {
        let mut lines = Vec::new();
        lines.push("# RetroArch input config — generated by Cubi Frontend".to_string());
        lines.push(format!("# Generated: {}", chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")));
        lines.push(String::new());
        lines.push(r#"input_driver = "sdl2""#.to_string());
        lines.push("input_player1_joypad_index = \"0\"".to_string());
        lines.push(String::new());

        for b in bindings {
            if b.button_index < 0 { continue; } // Unbound
            if let Some(key) = Self::ra_key(&b.action) {
                lines.push(format!("{} = \"{}\"", key, b.button_index));
            }
        }
        lines.push(String::new());
        lines.join("\n")
    }
}
