use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemInfo {
    pub id: String,
    pub name: String,
    pub full_name: String,
    pub extensions: Vec<String>,
    pub game_count: u32,
    pub rom_path: String,
    pub icon: Option<String>,
}

/// Static system definition used during scanning
#[derive(Debug, Clone)]
pub struct SystemDef {
    pub id: &'static str,
    pub name: &'static str,
    pub full_name: &'static str,
    pub extensions: &'static [&'static str],
    pub folder_names: &'static [&'static str],
}

pub fn get_system_registry() -> Vec<SystemDef> {
    vec![
        SystemDef {
            id: "nes",
            name: "NES",
            full_name: "Nintendo Entertainment System",
            extensions: &["nes", "fds", "unf", "zip", "7z"],
            folder_names: &["nes", "famicom", "nintendo"],
        },
        SystemDef {
            id: "snes",
            name: "SNES",
            full_name: "Super Nintendo Entertainment System",
            extensions: &["sfc", "smc", "fig", "bs", "zip", "7z"],
            folder_names: &["snes", "supernes", "supernintendo", "superfamicom"],
        },
        SystemDef {
            id: "n64",
            name: "N64",
            full_name: "Nintendo 64",
            extensions: &["n64", "z64", "v64", "zip", "7z"],
            folder_names: &["n64", "nintendo64"],
        },
        SystemDef {
            id: "gb",
            name: "Game Boy",
            full_name: "Nintendo Game Boy",
            extensions: &["gb", "sgb", "zip", "7z"],
            folder_names: &["gb", "gameboy"],
        },
        SystemDef {
            id: "gbc",
            name: "GBC",
            full_name: "Nintendo Game Boy Color",
            extensions: &["gbc", "zip", "7z"],
            folder_names: &["gbc", "gameboycolor"],
        },
        SystemDef {
            id: "gba",
            name: "GBA",
            full_name: "Nintendo Game Boy Advance",
            extensions: &["gba", "zip", "7z"],
            folder_names: &["gba", "gameboyadvance"],
        },
        SystemDef {
            id: "nds",
            name: "Nintendo DS",
            full_name: "Nintendo DS",
            extensions: &["nds", "zip", "7z"],
            folder_names: &["nds", "nintendods", "ds"],
        },
        SystemDef {
            id: "gamecube",
            name: "GameCube",
            full_name: "Nintendo GameCube",
            extensions: &["iso", "rvz", "gcz", "wbfs", "ciso"],
            folder_names: &["gamecube", "gc", "ngc"],
        },
        SystemDef {
            id: "wii",
            name: "Wii",
            full_name: "Nintendo Wii",
            extensions: &["iso", "rvz", "gcz", "wbfs", "ciso", "wad"],
            folder_names: &["wii"],
        },
        SystemDef {
            id: "wiiu",
            name: "Wii U",
            full_name: "Nintendo Wii U",
            extensions: &["rpx", "wud", "wux", "wua", "iso"],
            folder_names: &["wiiu", "wii-u", "wii u"],
        },
        SystemDef {
            id: "switch",
            name: "Switch",
            full_name: "Nintendo Switch",
            extensions: &["nsp", "xci", "nro"],
            folder_names: &["switch", "nswitch"],
        },
        SystemDef {
            id: "ps1",
            name: "PS1",
            full_name: "Sony PlayStation",
            extensions: &["cue", "bin", "iso", "chd", "pbp", "mds", "mdf"],
            folder_names: &["ps1", "psx", "playstation", "playstation1"],
        },
        SystemDef {
            id: "ps2",
            name: "PS2",
            full_name: "Sony PlayStation 2",
            extensions: &["iso", "chd", "cso", "gz"],
            folder_names: &["ps2", "playstation2"],
        },
        SystemDef {
            id: "ps3",
            name: "PS3",
            full_name: "Sony PlayStation 3",
            extensions: &["iso", "pkg", "bin"],
            folder_names: &["ps3", "playstation3", "rpcs3"],
        },
        SystemDef {
            id: "psp",
            name: "PSP",
            full_name: "Sony PlayStation Portable",
            extensions: &["iso", "cso", "pbp", "chd"],
            folder_names: &["psp", "playstationportable"],
        },
        SystemDef {
            id: "genesis",
            name: "Genesis",
            full_name: "Sega Genesis / Mega Drive",
            extensions: &["md", "bin", "gen", "smd", "zip", "7z"],
            folder_names: &["genesis", "megadrive", "sega-genesis", "sega-megadrive"],
        },
        SystemDef {
            id: "mastersystem",
            name: "Master System",
            full_name: "Sega Master System",
            extensions: &["sms", "zip", "7z"],
            folder_names: &["mastersystem", "sms"],
        },
        SystemDef {
            id: "saturn",
            name: "Saturn",
            full_name: "Sega Saturn",
            extensions: &["cue", "iso", "mdf", "chd"],
            folder_names: &["saturn", "segasaturn"],
        },
        SystemDef {
            id: "dreamcast",
            name: "Dreamcast",
            full_name: "Sega Dreamcast",
            extensions: &["cdi", "iso", "chd", "gdi"],
            folder_names: &["dreamcast", "dc"],
        },
        SystemDef {
            id: "xbox",
            name: "Xbox",
            full_name: "Microsoft Xbox",
            extensions: &["iso", "xbe"],
            folder_names: &["xbox"],
        },
        SystemDef {
            id: "arcade",
            name: "Arcade",
            full_name: "Arcade (MAME)",
            extensions: &["zip", "7z", "chd"],
            folder_names: &["arcade", "mame", "fba"],
        },
        SystemDef {
            id: "fbneo",
            name: "FBNeo",
            full_name: "FinalBurn Neo",
            extensions: &["zip", "7z", "chd"],
            folder_names: &["fbneo", "finalburn", "fbn", "finalburneo"],
        },
        SystemDef {
            id: "neogeo",
            name: "Neo Geo",
            full_name: "SNK Neo Geo",
            extensions: &["zip", "7z", "chd"],
            folder_names: &["neogeo", "neo-geo", "neo_geo", "ngeo"],
        },
        SystemDef {
            id: "cps1",
            name: "CPS-1",
            full_name: "Capcom Play System 1",
            extensions: &["zip", "7z"],
            folder_names: &["cps1", "cps-1"],
        },
        SystemDef {
            id: "cps2",
            name: "CPS-2",
            full_name: "Capcom Play System 2",
            extensions: &["zip", "7z"],
            folder_names: &["cps2", "cps-2"],
        },
        SystemDef {
            id: "cps3",
            name: "CPS-3",
            full_name: "Capcom Play System 3",
            extensions: &["zip", "7z"],
            folder_names: &["cps3", "cps-3"],
        },
        SystemDef {
            id: "amiga",
            name: "Amiga",
            full_name: "Commodore Amiga",
            extensions: &["adf", "lha", "hdf", "zip", "7z"],
            folder_names: &["amiga", "amiga500", "amiga600", "amiga1200", "commodore-amiga"],
        },
        SystemDef {
            id: "atari2600",
            name: "Atari 2600",
            full_name: "Atari 2600",
            extensions: &["a26", "bin", "rom", "zip", "7z"],
            folder_names: &["atari2600", "atari-2600", "2600"],
        },
        SystemDef {
            id: "atari5200",
            name: "Atari 5200",
            full_name: "Atari 5200",
            extensions: &["a52", "bin", "rom", "zip", "7z"],
            folder_names: &["atari5200", "atari-5200", "5200"],
        },
        SystemDef {
            id: "atari7800",
            name: "Atari 7800",
            full_name: "Atari 7800",
            extensions: &["a78", "bin", "rom", "zip", "7z"],
            folder_names: &["atari7800", "atari-7800", "7800"],
        },
        SystemDef {
            id: "atarist",
            name: "Atari ST",
            full_name: "Atari ST",
            extensions: &["st", "msa", "dim", "zip", "7z"],
            folder_names: &["atarist", "atari-st", "st"],
        },
        SystemDef {
            id: "atarilynx",
            name: "Atari Lynx",
            full_name: "Atari Lynx",
            extensions: &["lnx", "zip", "7z"],
            folder_names: &["atarilynx", "atari-lynx", "lynx"],
        },
        SystemDef {
            id: "pcengine",
            name: "PC Engine",
            full_name: "NEC PC Engine / TurboGrafx-16",
            extensions: &["pce", "cue", "bin", "chd", "zip", "7z"],
            folder_names: &["pcengine", "turbografx", "turbografx-16", "tg16", "pce"],
        },
        SystemDef {
            id: "gamegear",
            name: "Game Gear",
            full_name: "Sega Game Gear",
            extensions: &["gg", "zip", "7z"],
            folder_names: &["gamegear", "game-gear", "gg"],
        },
        SystemDef {
            id: "ngpc",
            name: "Neo Geo Pocket",
            full_name: "SNK Neo Geo Pocket Color",
            extensions: &["ngc", "ngp", "zip", "7z"],
            folder_names: &["ngpc", "neogeopocket", "ngp"],
        },
        SystemDef {
            id: "colecovision",
            name: "ColecoVision",
            full_name: "Coleco ColecoVision",
            extensions: &["col", "rom", "zip", "7z"],
            folder_names: &["colecovision", "coleco"],
        },
        SystemDef {
            id: "msx",
            name: "MSX",
            full_name: "MSX / MSX2",
            extensions: &["rom", "mx1", "mx2", "dsk", "cas", "zip", "7z"],
            folder_names: &["msx", "msx2"],
        },
        SystemDef {
            id: "c64",
            name: "C64",
            full_name: "Commodore 64",
            extensions: &["d64", "t64", "prg", "tap", "crt", "zip", "7z"],
            folder_names: &["c64", "commodore64", "commodore-64"],
        },
        SystemDef {
            id: "wswan",
            name: "WonderSwan",
            full_name: "Bandai WonderSwan Color",
            extensions: &["ws", "wsc", "zip", "7z"],
            folder_names: &["wswan", "wonderswan", "wsc"],
        },
        SystemDef {
            id: "3ds",
            name: "3DS",
            full_name: "Nintendo 3DS",
            extensions: &["3ds", "cia", "cxi"],
            folder_names: &["3ds", "nintendo3ds", "n3ds"],
        },
        // ── Systems added from ES-DE / EmuDeck ──────────────────────────
        SystemDef {
            id: "fds",
            name: "FDS",
            full_name: "Nintendo Famicom Disk System",
            extensions: &["fds", "zip", "7z"],
            folder_names: &["fds", "famicomdisk"],
        },
        SystemDef {
            id: "satellaview",
            name: "Satellaview",
            full_name: "Nintendo Satellaview",
            extensions: &["bs", "sfc", "zip", "7z"],
            folder_names: &["satellaview", "bs"],
        },
        SystemDef {
            id: "sg1000",
            name: "SG-1000",
            full_name: "Sega SG-1000",
            extensions: &["sg", "zip", "7z"],
            folder_names: &["sg1000", "sg-1000"],
        },
        SystemDef {
            id: "intellivision",
            name: "Intellivision",
            full_name: "Mattel Intellivision",
            extensions: &["int", "bin", "zip", "7z"],
            folder_names: &["intellivision"],
        },
        SystemDef {
            id: "wswanc",
            name: "WonderSwan Color",
            full_name: "Bandai WonderSwan Color",
            extensions: &["wsc", "zip", "7z"],
            folder_names: &["wswanc", "wonderswancolor"],
        },
        SystemDef {
            id: "psvita",
            name: "PS Vita",
            full_name: "Sony PlayStation Vita",
            extensions: &["vpk"],
            folder_names: &["psvita", "vita"],
        },
        SystemDef {
            id: "xbox360",
            name: "Xbox 360",
            full_name: "Microsoft Xbox 360",
            extensions: &["iso", "xex"],
            folder_names: &["xbox360", "xbox-360"],
        },
        SystemDef {
            id: "ps4",
            name: "PS4",
            full_name: "Sony PlayStation 4",
            extensions: &["pkg"],
            folder_names: &["ps4", "playstation4"],
        },
        SystemDef {
            id: "gw",
            name: "Game & Watch",
            full_name: "Nintendo Game & Watch",
            extensions: &["mgw", "zip", "7z"],
            folder_names: &["gw", "gameandwatch"],
        },
        SystemDef {
            id: "model2",
            name: "Model 2",
            full_name: "Sega Model 2 (Arcade)",
            extensions: &["zip", "7z"],
            folder_names: &["model2"],
        },
        SystemDef {
            id: "supermodel",
            name: "Supermodel",
            full_name: "Sega Model 3 (Arcade)",
            extensions: &["zip", "7z"],
            folder_names: &["supermodel", "model3"],
        },
        SystemDef {
            id: "atarijaguar",
            name: "Atari Jaguar",
            full_name: "Atari Jaguar",
            extensions: &["j64", "jag", "zip", "7z"],
            folder_names: &["atarijaguar", "jaguar"],
        },
        SystemDef {
            id: "scummvm",
            name: "ScummVM",
            full_name: "ScummVM",
            extensions: &["scummvm"],
            folder_names: &["scummvm"],
        },
        SystemDef {
            id: "3do",
            name: "3DO",
            full_name: "3DO Interactive Multiplayer",
            extensions: &["iso", "bin", "chd", "cue"],
            folder_names: &["3do"],
        },
        SystemDef {
            id: "megadrive",
            name: "Mega Drive",
            full_name: "Sega Mega Drive",
            extensions: &["md", "bin", "gen", "smd", "zip", "7z"],
            folder_names: &["megadrive", "mega-drive"],
        },
        // ── Additional systems ───────────────────────────────────────────
        SystemDef {
            id: "segacd",
            name: "Sega CD",
            full_name: "Sega CD / Mega CD",
            extensions: &["cue", "iso", "chd", "bin"],
            folder_names: &["segacd", "sega-cd", "megacd", "mega-cd"],
        },
        SystemDef {
            id: "sega32x",
            name: "32X",
            full_name: "Sega 32X",
            extensions: &["32x", "bin", "smd", "zip", "7z"],
            folder_names: &["sega32x", "32x", "sega-32x"],
        },
        SystemDef {
            id: "virtualboy",
            name: "Virtual Boy",
            full_name: "Nintendo Virtual Boy",
            extensions: &["vb", "vboy", "zip", "7z"],
            folder_names: &["virtualboy", "vboy", "vb"],
        },
        SystemDef {
            id: "neocd",
            name: "Neo Geo CD",
            full_name: "SNK Neo Geo CD",
            extensions: &["cue", "chd", "iso"],
            folder_names: &["neocd", "neogeocd", "neo-geo-cd"],
        },
        SystemDef {
            id: "pcenginecd",
            name: "PC Engine CD",
            full_name: "NEC PC Engine CD / TurboGrafx-CD",
            extensions: &["cue", "chd", "iso", "bin"],
            folder_names: &["pcenginecd", "pcecd", "turbografx-cd", "tg-cd"],
        },
        SystemDef {
            id: "supergrafx",
            name: "SuperGrafx",
            full_name: "NEC SuperGrafx",
            extensions: &["pce", "sgx", "zip", "7z"],
            folder_names: &["supergrafx", "sgfx", "sgx"],
        },
        SystemDef {
            id: "vectrex",
            name: "Vectrex",
            full_name: "GCE Vectrex",
            extensions: &["vec", "bin", "zip", "7z"],
            folder_names: &["vectrex"],
        },
        SystemDef {
            id: "dos",
            name: "DOS",
            full_name: "MS-DOS",
            extensions: &["exe", "com", "bat", "conf", "zip", "7z"],
            folder_names: &["dos", "msdos", "dosbox"],
        },
        SystemDef {
            id: "zxspectrum",
            name: "ZX Spectrum",
            full_name: "Sinclair ZX Spectrum",
            extensions: &["tzx", "tap", "z80", "sna", "szx", "dsk", "zip", "7z"],
            folder_names: &["zxspectrum", "zx-spectrum", "spectrum"],
        },
        SystemDef {
            id: "odyssey2",
            name: "Odyssey 2",
            full_name: "Magnavox Odyssey 2 / Philips Videopac",
            extensions: &["bin", "zip", "7z"],
            folder_names: &["odyssey2", "odyssey-2", "videopac", "o2em"],
        },
        SystemDef {
            id: "pcfx",
            name: "PC-FX",
            full_name: "NEC PC-FX",
            extensions: &["cue", "chd", "iso"],
            folder_names: &["pcfx", "pc-fx"],
        },
        SystemDef {
            id: "x68000",
            name: "X68000",
            full_name: "Sharp X68000",
            extensions: &["dim", "hdf", "xdf", "2hd", "d88", "cmd", "zip", "7z"],
            folder_names: &["x68000", "x68k"],
        },
        SystemDef {
            id: "pokemini",
            name: "Pokemon Mini",
            full_name: "Nintendo Pokemon Mini",
            extensions: &["min", "zip", "7z"],
            folder_names: &["pokemini", "pokemon-mini"],
        },
        SystemDef {
            id: "channelf",
            name: "Channel F",
            full_name: "Fairchild Channel F",
            extensions: &["bin", "chf", "zip", "7z"],
            folder_names: &["channelf", "channel-f", "fairchild"],
        },
        SystemDef {
            id: "jagcd",
            name: "Jaguar CD",
            full_name: "Atari Jaguar CD",
            extensions: &["cue", "iso", "chd"],
            folder_names: &["jaguarcd", "jagcd", "atari-jaguar-cd"],
        },
        SystemDef {
            id: "n64dd",
            name: "64DD",
            full_name: "Nintendo 64DD",
            extensions: &["ndd", "d64", "zip", "7z"],
            folder_names: &["n64dd", "64dd"],
        },
        SystemDef {
            id: "sufami",
            name: "Sufami Turbo",
            full_name: "Bandai Sufami Turbo",
            extensions: &["sfc", "smc", "zip", "7z"],
            folder_names: &["sufami", "sufamiturbo"],
        },
        SystemDef {
            id: "pico",
            name: "Sega Pico",
            full_name: "Sega Pico",
            extensions: &["md", "bin", "zip", "7z"],
            folder_names: &["pico", "segapico"],
        },
        SystemDef {
            id: "flash",
            name: "Flash",
            full_name: "Adobe Flash",
            extensions: &["swf", "spl"],
            folder_names: &["flash", "flashgames", "flash-games"],
        },
        SystemDef {
            id: "mugen",
            name: "MUGEN",
            full_name: "M.U.G.E.N",
            extensions: &["lnk"],
            folder_names: &["mugen", "m.u.g.e.n"],
        },
        SystemDef {
            id: "android",
            name: "Android",
            full_name: "Android",
            extensions: &["lnk"],
            folder_names: &["android"],
        },
        SystemDef {
            id: "web",
            name: "Web",
            full_name: "Web Apps",
            extensions: &["url", "lnk"],
            folder_names: &["web"],
        },
    ]
}
