use crate::models::SystemWiki;

/// Get the builtin wiki data for all known systems.
/// This is seeded on first launch and can be edited by the user.
pub fn get_builtin_wiki_data() -> Vec<SystemWiki> {
    vec![
        // ── Nintendo ────────────────────────────────────────────
        SystemWiki {
            system_id: "nes".into(),
            manufacturer: "Nintendo".into(),
            release_year: Some(1983),
            discontinue_year: Some(2003),
            generation: Some(3),
            media_type: "Cartridge".into(),
            cpu: "Ricoh 2A03 (MOS 6502) @ 1.79 MHz".into(),
            memory: "2 KB RAM, 2 KB VRAM".into(),
            graphics: "Ricoh PPU, 256×240, 54 colors".into(),
            sound: "5 channels (2 pulse, 1 triangle, 1 noise, 1 DPCM)".into(),
            display: "240p NTSC / 288p PAL".into(),
            units_sold: "61.91 million".into(),
            launch_price: "$199 USD (1985)".into(),
            description: "The Nintendo Entertainment System (NES) is an 8-bit home video game console developed and manufactured by Nintendo. It was first released in Japan in 1983 as the Family Computer (Famicom), and in North America in 1985. The NES helped revitalize the US video game industry following the crash of 1983, and set the standard for console design, game licensing, and controller layout. It introduced iconic franchises including Super Mario Bros., The Legend of Zelda, and Metroid.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Nintendo_Entertainment_System".into(),
            image_url: String::new(),
            notable_games: "Super Mario Bros., The Legend of Zelda, Metroid, Mega Man 2, Castlevania, Contra, Final Fantasy, Dragon Quest, Punch-Out!!, Kirby's Adventure".into(),
            emulators: "RetroArch (FCEUmm, Mesen, Nestopia), FCEUX, Mesen".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "snes".into(),
            manufacturer: "Nintendo".into(),
            release_year: Some(1990),
            discontinue_year: Some(2003),
            generation: Some(4),
            media_type: "Cartridge".into(),
            cpu: "Ricoh 5A22 (65C816) @ 3.58 MHz".into(),
            memory: "128 KB RAM, 64 KB VRAM".into(),
            graphics: "S-PPU, 256×224 to 512×448, 32768 colors".into(),
            sound: "Sony SPC700, 8 channels, 16-bit ADPCM".into(),
            display: "240p / 480i".into(),
            units_sold: "49.10 million".into(),
            launch_price: "$199 USD (1991)".into(),
            description: "The Super Nintendo Entertainment System (SNES) is a 16-bit home video game console developed by Nintendo. Released in Japan as the Super Famicom in 1990 and in North America in 1991, it was a major competitor to the Sega Genesis. The SNES features advanced graphics and sound capabilities including Mode 7 scaling/rotation. It is home to some of the most acclaimed games of all time including Chrono Trigger, Super Metroid, and The Legend of Zelda: A Link to the Past.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Super_Nintendo_Entertainment_System".into(),
            image_url: String::new(),
            notable_games: "Super Mario World, Zelda: A Link to the Past, Chrono Trigger, Super Metroid, Final Fantasy VI, Donkey Kong Country, Street Fighter II, EarthBound, Mega Man X, Secret of Mana".into(),
            emulators: "RetroArch (Snes9x, bsnes), Snes9x, bsnes, Mesen-S".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "n64".into(),
            manufacturer: "Nintendo".into(),
            release_year: Some(1996),
            discontinue_year: Some(2002),
            generation: Some(5),
            media_type: "Cartridge".into(),
            cpu: "NEC VR4300 (MIPS R4300i) @ 93.75 MHz".into(),
            memory: "4 MB RDRAM (8 MB with Expansion Pak)".into(),
            graphics: "Reality Coprocessor (RCP), 64-bit".into(),
            sound: "16-bit, 100 channels (software mixed)".into(),
            display: "240p, 480i, 480p (rare)".into(),
            units_sold: "32.93 million".into(),
            launch_price: "$199.99 USD".into(),
            description: "The Nintendo 64 (N64) is a home video game console developed and marketed by Nintendo. Named for its 64-bit central processing unit, it was released in 1996. The N64 was the last major home console to use cartridges as its primary storage format. It pioneered 3D gameplay with titles like Super Mario 64 and introduced the analog stick to mainstream gaming. The console featured four controller ports for local multiplayer, leading to iconic party games like GoldenEye 007 and Mario Kart 64.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Nintendo_64".into(),
            image_url: String::new(),
            notable_games: "Super Mario 64, Zelda: Ocarina of Time, GoldenEye 007, Mario Kart 64, Super Smash Bros., Banjo-Kazooie, Paper Mario, Star Fox 64, Perfect Dark, Majora's Mask".into(),
            emulators: "RetroArch (Mupen64Plus-Next, ParaLLEl N64), Project64, simple64, Ares".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "gamecube".into(),
            manufacturer: "Nintendo".into(),
            release_year: Some(2001),
            discontinue_year: Some(2007),
            generation: Some(6),
            media_type: "miniDVD (1.5 GB)".into(),
            cpu: "IBM PowerPC Gekko @ 485 MHz".into(),
            memory: "24 MB RAM + 16 MB ARAM".into(),
            graphics: "ATI Flipper @ 162 MHz".into(),
            sound: "Macronix 16-bit DSP".into(),
            display: "480i, 480p".into(),
            units_sold: "21.74 million".into(),
            launch_price: "$199.99 USD".into(),
            description: "The Nintendo GameCube is a home video game console released by Nintendo in 2001. It is the first Nintendo console to use optical discs as its primary storage medium, using proprietary miniDVD-based discs. Despite relatively modest sales compared to the PlayStation 2 and Xbox, it boasted a library of critically acclaimed exclusives. The system featured a distinctive compact cube design and offered connectivity with the Game Boy Advance via link cable.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/GameCube".into(),
            image_url: String::new(),
            notable_games: "Super Smash Bros. Melee, Zelda: Wind Waker, Metroid Prime, Resident Evil 4, Super Mario Sunshine, Luigi's Mansion, Animal Crossing, F-Zero GX, Paper Mario: TTYD, Pikmin".into(),
            emulators: "Dolphin, RetroArch (Dolphin)".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "wii".into(),
            manufacturer: "Nintendo".into(),
            release_year: Some(2006),
            discontinue_year: Some(2013),
            generation: Some(7),
            media_type: "Wii Optical Disc (4.7 / 8.54 GB)".into(),
            cpu: "IBM PowerPC Broadway @ 729 MHz".into(),
            memory: "88 MB (24 MB MEM1 + 64 MB MEM2)".into(),
            graphics: "ATI Hollywood @ 243 MHz".into(),
            sound: "DSP, Dolby Pro Logic II".into(),
            display: "480i, 480p".into(),
            units_sold: "101.63 million".into(),
            launch_price: "$249.99 USD".into(),
            description: "The Wii is a home video game console released by Nintendo in 2006. A defining feature of the console is its wireless controller, the Wii Remote, which can be used as a motion-sensor pointing device and detects movement in three dimensions. The Wii became a massive cultural phenomenon, attracting casual gamers and non-gamers with titles like Wii Sports, which became the best-selling single-platform game at the time. It was fully backward compatible with GameCube games and controllers.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Wii".into(),
            image_url: String::new(),
            notable_games: "Wii Sports, Super Mario Galaxy, Zelda: Twilight Princess, Super Smash Bros. Brawl, Mario Kart Wii, Xenoblade Chronicles, Donkey Kong Country Returns, Metroid Prime 3, New Super Mario Bros. Wii".into(),
            emulators: "Dolphin, RetroArch (Dolphin)".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "wiiu".into(),
            manufacturer: "Nintendo".into(),
            release_year: Some(2012),
            discontinue_year: Some(2017),
            generation: Some(8),
            media_type: "Wii U Optical Disc (25 GB)".into(),
            cpu: "IBM PowerPC Espresso (tri-core @ 1.24 GHz)".into(),
            memory: "2 GB (1 GB for games)".into(),
            graphics: "AMD Radeon (Latte) @ 550 MHz".into(),
            sound: "DSP, HDMI audio".into(),
            display: "1080p, 720p, 480p".into(),
            units_sold: "13.56 million".into(),
            launch_price: "$299.99 / $349.99 USD".into(),
            description: "The Wii U is a home video game console developed by Nintendo as the successor to the Wii. Released in 2012, its distinguishing feature is the GamePad controller with an integrated 6.2-inch touchscreen, enabling off-TV play and asymmetric gameplay. Despite being the first eighth-generation console, it struggled commercially due to confusion over whether it was a new console or a Wii accessory. However, it produced several excellent games that were later ported to the Nintendo Switch.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Wii_U".into(),
            image_url: String::new(),
            notable_games: "Super Mario 3D World, Zelda: Breath of the Wild, Splatoon, Super Smash Bros. for Wii U, Mario Kart 8, Bayonetta 2, Xenoblade Chronicles X, Super Mario Maker, Pikmin 3, Donkey Kong Country: Tropical Freeze".into(),
            emulators: "Cemu".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "switch".into(),
            manufacturer: "Nintendo".into(),
            release_year: Some(2017),
            discontinue_year: None,
            generation: Some(8),
            media_type: "Game Card (32 GB), Digital".into(),
            cpu: "NVIDIA Tegra X1 (ARM Cortex-A57 quad-core @ 1.02 GHz)".into(),
            memory: "4 GB LPDDR4".into(),
            graphics: "NVIDIA Maxwell (256 CUDA cores @ 307-768 MHz)".into(),
            sound: "Stereo, USB audio".into(),
            display: "720p portable / 1080p docked".into(),
            units_sold: "143+ million".into(),
            launch_price: "$299.99 USD".into(),
            description: "The Nintendo Switch is a hybrid home/portable video game console developed by Nintendo. Released in March 2017, it can be used as a home console connected to a TV or as a portable handheld device. The Switch features detachable Joy-Con controllers that support motion controls and HD Rumble. It became one of the best-selling consoles ever, revitalizing Nintendo's home console business with blockbuster titles like The Legend of Zelda: Breath of the Wild and Animal Crossing: New Horizons.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Nintendo_Switch".into(),
            image_url: String::new(),
            notable_games: "Zelda: Breath of the Wild, Super Mario Odyssey, Animal Crossing: New Horizons, Splatoon 3, Mario Kart 8 Deluxe, Super Smash Bros. Ultimate, Zelda: Tears of the Kingdom, Xenoblade Chronicles 3, Metroid Dread".into(),
            emulators: "Ryujinx, Suyu".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "gb".into(),
            manufacturer: "Nintendo".into(),
            release_year: Some(1989),
            discontinue_year: Some(2003),
            generation: Some(4),
            media_type: "Cartridge".into(),
            cpu: "Sharp LR35902 (modified Z80) @ 4.19 MHz".into(),
            memory: "8 KB RAM, 8 KB VRAM".into(),
            graphics: "160×144, 4 shades of green".into(),
            sound: "4 channels (2 pulse, 1 wave, 1 noise)".into(),
            display: "160×144 LCD, monochrome".into(),
            units_sold: "118.69 million (with GBC)".into(),
            launch_price: "$89.99 USD".into(),
            description: "The Game Boy is an 8-bit handheld game console developed and manufactured by Nintendo. Released in 1989, it became the first successful handheld gaming console, selling over 118 million units combined with the Game Boy Color. Despite technically inferior hardware compared to competitors like the Atari Lynx and Sega Game Gear, the Game Boy dominated thanks to its long battery life, robust build quality, and the killer app Tetris, which was bundled with the system.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Game_Boy".into(),
            image_url: String::new(),
            notable_games: "Tetris, Pokemon Red/Blue, Link's Awakening, Super Mario Land 2, Kirby's Dream Land, Metroid II, Donkey Kong, Mega Man V, Wario Land, Final Fantasy Legend".into(),
            emulators: "RetroArch (Gambatte, SameBoy, mGBA), mGBA, SameBoy, BGB".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "gbc".into(),
            manufacturer: "Nintendo".into(),
            release_year: Some(1998),
            discontinue_year: Some(2003),
            generation: Some(4),
            media_type: "Cartridge".into(),
            cpu: "Sharp LR35902 @ 4.19 / 8.39 MHz".into(),
            memory: "32 KB RAM, 16 KB VRAM".into(),
            graphics: "160×144, 56 colors on screen (32768 palette)".into(),
            sound: "Same as Game Boy, 4 channels".into(),
            display: "160×144 TFT LCD, color".into(),
            units_sold: "(included in GB total)".into(),
            launch_price: "$79.99 USD".into(),
            description: "The Game Boy Color (GBC) is a handheld game console manufactured by Nintendo in 1998. It is the successor to the Game Boy and features a color screen. It is backward compatible with original Game Boy games. The GBC was a transitional device between the original Game Boy and the Game Boy Advance, and hosted landmark titles like Pokemon Gold/Silver and The Legend of Zelda: Oracle series.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Game_Boy_Color".into(),
            image_url: String::new(),
            notable_games: "Pokemon Gold/Silver/Crystal, Zelda: Oracle of Ages/Seasons, Wario Land 3, Dragon Quest Monsters, Metal Gear Solid, Mario Tennis, Shantae".into(),
            emulators: "RetroArch (Gambatte, SameBoy, mGBA), mGBA, SameBoy, BGB".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "gba".into(),
            manufacturer: "Nintendo".into(),
            release_year: Some(2001),
            discontinue_year: Some(2010),
            generation: Some(6),
            media_type: "Cartridge".into(),
            cpu: "ARM7TDMI @ 16.78 MHz".into(),
            memory: "32 KB internal, 256 KB external RAM".into(),
            graphics: "240×160, 32768 colors".into(),
            sound: "6 channels (4 legacy + 2 PCM)".into(),
            display: "240×160 TFT LCD".into(),
            units_sold: "81.51 million".into(),
            launch_price: "$99.99 USD".into(),
            description: "The Game Boy Advance (GBA) is a 32-bit handheld game console developed, manufactured and marketed by Nintendo as the successor to the Game Boy Color. It was released in 2001 and features a wider screen and significantly more powerful hardware. The GBA is backward compatible with Game Boy and Game Boy Color games. It served as a portable SNES-quality platform, hosting exceptional ports and original titles including the Metroid Fusion, Pokemon, and Fire Emblem franchises.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Game_Boy_Advance".into(),
            image_url: String::new(),
            notable_games: "Pokemon Ruby/Sapphire, Metroid Fusion, Zelda: Minish Cap, Fire Emblem, Golden Sun, Advance Wars, Castlevania: Aria of Sorrow, Mario & Luigi, Final Fantasy Tactics Advance, WarioWare".into(),
            emulators: "RetroArch (mGBA, VBA-M), mGBA, VBA-M".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "nds".into(),
            manufacturer: "Nintendo".into(),
            release_year: Some(2004),
            discontinue_year: Some(2013),
            generation: Some(7),
            media_type: "Game Card".into(),
            cpu: "ARM9 @ 67 MHz + ARM7 @ 33 MHz".into(),
            memory: "4 MB RAM + 656 KB VRAM".into(),
            graphics: "Dual 256×192 screens, 3D rendering".into(),
            sound: "16 channels, stereo".into(),
            display: "Dual 3\" TFT LCD (256×192 each), touchscreen".into(),
            units_sold: "154.02 million".into(),
            launch_price: "$149.99 USD".into(),
            description: "The Nintendo DS is a dual-screen handheld game console developed and manufactured by Nintendo, released in 2004. The DS stands for 'Dual Screen', featuring two LCD screens, the lower being a touchscreen. It introduced innovative gameplay mechanics through its touch and microphone inputs. The DS became the second best-selling handheld console in history after the original Game Boy line. It was followed by the DSi revision with added cameras and digital storefront.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Nintendo_DS".into(),
            image_url: String::new(),
            notable_games: "New Super Mario Bros., Pokemon Diamond/Pearl, Zelda: Phantom Hourglass, Mario Kart DS, Brain Age, Animal Crossing: Wild World, Chrono Trigger, Phoenix Wright, The World Ends with You, Dragon Quest IX".into(),
            emulators: "RetroArch (melonDS, DeSmuME), melonDS, DeSmuME".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "3ds".into(),
            manufacturer: "Nintendo".into(),
            release_year: Some(2011),
            discontinue_year: Some(2020),
            generation: Some(8),
            media_type: "Game Card, Digital".into(),
            cpu: "ARM11 MPCore dual-core @ 268 MHz + ARM9".into(),
            memory: "128 MB FCRAM + 6 MB VRAM".into(),
            graphics: "DMP PICA200 (stereo 3D without glasses)".into(),
            sound: "Stereo speakers, surround".into(),
            display: "3.53\" widescreen (400×240 per eye) + 3.02\" touchscreen (320×240)".into(),
            units_sold: "75.94 million".into(),
            launch_price: "$249.99 USD".into(),
            description: "The Nintendo 3DS is a handheld game console produced by Nintendo, released in 2011. It is capable of displaying stereoscopic 3D effects without the use of 3D glasses or additional accessories. The 3DS succeeded the Nintendo DS and featured improved hardware, StreetPass/SpotPass wireless connectivity, augmented reality, and a built-in gyroscope. The system saw multiple hardware revisions including the 2DS, New 3DS, and New 2DS XL.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Nintendo_3DS".into(),
            image_url: String::new(),
            notable_games: "Pokemon X/Y, Zelda: A Link Between Worlds, Fire Emblem: Awakening, Super Mario 3D Land, Monster Hunter 4 Ultimate, Animal Crossing: New Leaf, Bravely Default, Metroid: Samus Returns, Kid Icarus: Uprising".into(),
            emulators: "Citra (discontinued), Lime3DS, RetroArch (Citra)".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "fds".into(),
            manufacturer: "Nintendo".into(),
            release_year: Some(1986),
            discontinue_year: Some(2003),
            generation: Some(3),
            media_type: "Floppy Disk (Disk Card)".into(),
            cpu: "Same as Famicom (Ricoh 2A03)".into(),
            memory: "32 KB RAM (disk adapter adds 32 KB)".into(),
            graphics: "Same as Famicom + extra wavetable sound".into(),
            sound: "Extra wavetable sound channel".into(),
            display: "240p".into(),
            units_sold: "4.44 million".into(),
            launch_price: "¥15,000 (~$100 USD)".into(),
            description: "The Famicom Disk System (FDS) is a peripheral for the Family Computer (Famicom) released by Nintendo in 1986 in Japan only. It uses proprietary floppy disks called 'Disk Cards' that provided larger and cheaper storage than cartridges, along with the ability to save game data. Many classic games debuted on FDS including the original versions of Zelda, Metroid, and Kid Icarus. It was never officially released outside of Japan.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Famicom_Disk_System".into(),
            image_url: String::new(),
            notable_games: "The Legend of Zelda, Metroid, Kid Icarus, Doki Doki Panic, Castlevania, Zelda II, Shin Onigashima".into(),
            emulators: "RetroArch (FCEUmm, Mesen, Nestopia), FCEUX, Mesen".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "satellaview".into(),
            manufacturer: "Nintendo / St.GIGA".into(),
            release_year: Some(1995),
            discontinue_year: Some(2000),
            generation: Some(4),
            media_type: "Satellite Broadcast (BS-X)".into(),
            cpu: "Same as Super Famicom".into(),
            memory: "Same as Super Famicom + 1 Mbit flash".into(),
            graphics: "Same as Super Famicom".into(),
            sound: "Same as Super Famicom".into(),
            display: "240p".into(),
            units_sold: "~100,000".into(),
            launch_price: "¥18,000 (~$170 USD)".into(),
            description: "The Satellaview is a satellite modem peripheral for the Super Famicom released only in Japan in 1995. It received content via satellite broadcasts by St.GIGA. Games were downloaded to 8M Memory Packs. It featured exclusive games and enhanced versions of existing titles, some with voiced narration only available during live broadcasts. Many Satellaview games are now considered lost media.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Satellaview".into(),
            image_url: String::new(),
            notable_games: "BS Zelda, BS Fire Emblem, BS F-Zero Grand Prix, Radical Dreamers, BS Super Mario USA, Excitebike: Bunbun Mario Battle".into(),
            emulators: "RetroArch (Snes9x, bsnes), Snes9x, bsnes".into(),
            updated_at: None,
        },

        // ── Sega ────────────────────────────────────────────────
        SystemWiki {
            system_id: "mastersystem".into(),
            manufacturer: "Sega".into(),
            release_year: Some(1985),
            discontinue_year: Some(1996),
            generation: Some(3),
            media_type: "Cartridge, Sega Card".into(),
            cpu: "Zilog Z80 @ 3.58 MHz".into(),
            memory: "8 KB RAM, 16 KB VRAM".into(),
            graphics: "VDP (TMS9918 derivative), 256×192, 64 colors".into(),
            sound: "SN76489, 4 channels + YM2413 FM (Japan)".into(),
            display: "240p".into(),
            units_sold: "~13 million".into(),
            launch_price: "$200 USD (1986)".into(),
            description: "The Sega Master System (SMS) is a third-generation home video game console manufactured by Sega. Released in 1985 in Japan and 1986 in North America, it competed with the NES but had limited success in North America and Japan. However, it achieved significant popularity in Europe, Brazil, and other markets, where Sega established a loyal fanbase. The system was technically superior to the NES in several ways, including a larger color palette.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Master_System".into(),
            image_url: String::new(),
            notable_games: "Alex Kidd in Miracle World, Phantasy Star, Sonic the Hedgehog, Wonder Boy III, Shinobi, R-Type, Hang-On, Space Harrier".into(),
            emulators: "RetroArch (Genesis Plus GX, PicoDrive), Kega Fusion, Emulicious".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "genesis".into(),
            manufacturer: "Sega".into(),
            release_year: Some(1988),
            discontinue_year: Some(1997),
            generation: Some(4),
            media_type: "Cartridge".into(),
            cpu: "Motorola 68000 @ 7.67 MHz + Z80 @ 3.58 MHz".into(),
            memory: "64 KB RAM, 64 KB VRAM, 8 KB Z80 RAM".into(),
            graphics: "VDP, 320×224, 512 colors (61 on-screen)".into(),
            sound: "Yamaha YM2612 FM (6 ch) + SN76489 PSG (4 ch)".into(),
            display: "240p, 480i".into(),
            units_sold: "30.75 million".into(),
            launch_price: "$189.99 USD (1989)".into(),
            description: "The Sega Genesis (known as Mega Drive outside North America) is a 16-bit fourth-generation home video game console. Released in 1988 in Japan and 1989 in North America, it was Sega's most successful console. The Genesis was the main rival to the SNES in the fierce 'console wars' of the early 1990s. Its aggressive marketing ('Genesis does what Nintendon't') and strong arcade ports made it especially popular in North America. Sonic the Hedgehog became the system's mascot and one of gaming's most iconic characters.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Sega_Genesis".into(),
            image_url: String::new(),
            notable_games: "Sonic the Hedgehog 1-3, Streets of Rage 2, Phantasy Star IV, Shining Force II, Gunstar Heroes, Castlevania: Bloodlines, ToeJam & Earl, Ecco the Dolphin, Comix Zone, Shinobi III".into(),
            emulators: "RetroArch (Genesis Plus GX, PicoDrive, BlastEm), Kega Fusion, BlastEm".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "megadrive".into(),
            manufacturer: "Sega".into(),
            release_year: Some(1988),
            discontinue_year: Some(1997),
            generation: Some(4),
            media_type: "Cartridge".into(),
            cpu: "Motorola 68000 @ 7.67 MHz + Z80 @ 3.58 MHz".into(),
            memory: "64 KB RAM, 64 KB VRAM".into(),
            graphics: "VDP, 320×224, 512 colors".into(),
            sound: "Yamaha YM2612 FM (6 ch) + SN76489 PSG (4 ch)".into(),
            display: "240p, 480i".into(),
            units_sold: "30.75 million".into(),
            launch_price: "¥21,000 (Japan)".into(),
            description: "The Mega Drive is the Japanese and European name for the Sega Genesis. Identical hardware to the Genesis, the Mega Drive name was used in all markets except North America. It was particularly successful in Europe and Brazil, where it maintained strong third-party support.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Sega_Genesis".into(),
            image_url: String::new(),
            notable_games: "Sonic the Hedgehog, Streets of Rage 2, Phantasy Star IV, Gunstar Heroes, Shining Force II".into(),
            emulators: "RetroArch (Genesis Plus GX, PicoDrive, BlastEm), Kega Fusion, BlastEm".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "gamegear".into(),
            manufacturer: "Sega".into(),
            release_year: Some(1990),
            discontinue_year: Some(1997),
            generation: Some(4),
            media_type: "Cartridge".into(),
            cpu: "Zilog Z80 @ 3.58 MHz".into(),
            memory: "8 KB RAM, 16 KB VRAM".into(),
            graphics: "160×144, 4096 colors (32 on-screen)".into(),
            sound: "SN76489, 3 tone + 1 noise".into(),
            display: "160×144 backlit color LCD".into(),
            units_sold: "~11 million".into(),
            launch_price: "$149.99 USD".into(),
            description: "The Sega Game Gear is an 8-bit handheld game console released by Sega in 1990. It was designed as a portable version of the Master System and competed primarily with the Game Boy. The Game Gear featured a backlit full-color screen, a significant advantage over the Game Boy's unlit monochrome display, but at the cost of much shorter battery life (about 3-5 hours on 6 AA batteries). It could play Master System games via an adapter accessory.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Game_Gear".into(),
            image_url: String::new(),
            notable_games: "Sonic the Hedgehog, Shinobi, Columns, Castle of Illusion, Shining Force, Defenders of Oasis, Sonic Triple Trouble".into(),
            emulators: "RetroArch (Genesis Plus GX, PicoDrive), Kega Fusion, Emulicious".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "sg1000".into(),
            manufacturer: "Sega".into(),
            release_year: Some(1983),
            discontinue_year: Some(1985),
            generation: Some(3),
            media_type: "Cartridge, Sega Card".into(),
            cpu: "NEC 780C (Z80 clone) @ 3.58 MHz".into(),
            memory: "2 KB RAM, 16 KB VRAM".into(),
            graphics: "TMS9918, 256×192, 16 colors".into(),
            sound: "SN76489, 3 tone + 1 noise".into(),
            display: "240p".into(),
            units_sold: "~2 million".into(),
            launch_price: "¥15,000".into(),
            description: "The SG-1000 is a home video game console manufactured by Sega, released in Japan on July 15, 1983 — the same day as the Nintendo Famicom. It was Sega's first entry into the home console market. While commercially overshadowed by the Famicom in Japan, it laid the groundwork for Sega's subsequent Master System. The hardware is closely related to the ColecoVision and MSX.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/SG-1000".into(),
            image_url: String::new(),
            notable_games: "Flicky, Girl's Garden, Congo Bongo, Champion Baseball, Star Jacker".into(),
            emulators: "RetroArch (Genesis Plus GX, blueMSX), Kega Fusion".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "saturn".into(),
            manufacturer: "Sega".into(),
            release_year: Some(1994),
            discontinue_year: Some(2000),
            generation: Some(5),
            media_type: "CD-ROM".into(),
            cpu: "Dual Hitachi SH-2 @ 28.6 MHz".into(),
            memory: "2 MB RAM + 1.5 MB VRAM".into(),
            graphics: "VDP1 (sprites) + VDP2 (backgrounds), 2D powerhouse".into(),
            sound: "Yamaha YMF292 (SCSP), 32 channels".into(),
            display: "240p, 480i".into(),
            units_sold: "9.26 million".into(),
            launch_price: "$399.99 USD".into(),
            description: "The Sega Saturn is a 32-bit fifth-generation home video game console developed by Sega, released in 1994 in Japan and 1995 in North America. Despite its powerful hardware featuring dual CPUs, the Saturn's complex architecture made it difficult to develop for. It struggled against the PlayStation in Western markets but was very successful in Japan, where it hosted excellent 2D fighting games, RPGs, and shoot-em-ups. Many Saturn exclusives remain highly sought-after today.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Sega_Saturn".into(),
            image_url: String::new(),
            notable_games: "Nights into Dreams, Panzer Dragoon Saga, Radiant Silvergun, Guardian Heroes, Virtua Fighter 2, Burning Rangers, Shining Force III, Dragon Force, Saturn Bomberman".into(),
            emulators: "RetroArch (Beetle Saturn, Kronos), Mednafen, SSF".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "dreamcast".into(),
            manufacturer: "Sega".into(),
            release_year: Some(1998),
            discontinue_year: Some(2001),
            generation: Some(6),
            media_type: "GD-ROM (1.2 GB)".into(),
            cpu: "Hitachi SH4 @ 200 MHz".into(),
            memory: "16 MB RAM + 8 MB VRAM".into(),
            graphics: "NEC PowerVR2, ~3M polygons/sec".into(),
            sound: "Yamaha AICA (ARM7), 64 channels".into(),
            display: "480p (VGA), 480i".into(),
            units_sold: "9.13 million".into(),
            launch_price: "$199 USD".into(),
            description: "The Dreamcast is a home video game console released by Sega on November 27, 1998 in Japan and September 9, 1999 in North America. It was the first sixth-generation console, launching before the PS2, Xbox, and GameCube. The Dreamcast was the first console with a built-in modem for online gaming. Despite critical acclaim and a strong launch, the Dreamcast was discontinued in 2001 as Sega exited the hardware business. It remains beloved for its innovative library and is considered ahead of its time.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Dreamcast".into(),
            image_url: String::new(),
            notable_games: "Shenmue, Sonic Adventure, SoulCalibur, Jet Set Radio, Crazy Taxi, Skies of Arcadia, Power Stone, Ikaruga, Rez, Phantasy Star Online".into(),
            emulators: "RetroArch (Flycast), Flycast, Redream, DEmul".into(),
            updated_at: None,
        },

        // ── Sony ────────────────────────────────────────────────
        SystemWiki {
            system_id: "ps1".into(),
            manufacturer: "Sony".into(),
            release_year: Some(1994),
            discontinue_year: Some(2006),
            generation: Some(5),
            media_type: "CD-ROM".into(),
            cpu: "MIPS R3000A @ 33.87 MHz".into(),
            memory: "2 MB RAM + 1 MB VRAM".into(),
            graphics: "GPU, 360,000 polygons/sec".into(),
            sound: "SPU, 24 channels, 16-bit ADPCM".into(),
            display: "240p, 480i".into(),
            units_sold: "102.49 million".into(),
            launch_price: "$299 USD".into(),
            description: "The PlayStation (PS1) is a home video game console developed and marketed by Sony Computer Entertainment. Released in 1994 in Japan and 1995 worldwide, it was Sony's first foray into the gaming console market, originally conceived as a CD-ROM add-on for the SNES. The PlayStation became the first console to ship over 100 million units, establishing Sony as a dominant force in gaming. It was instrumental in making 3D gaming mainstream and established the CD-ROM as the standard media for console games. The PS1 hosted genre-defining titles across RPGs, survival horror, fighting, and platforming.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/PlayStation_(console)".into(),
            image_url: String::new(),
            notable_games: "Final Fantasy VII, Metal Gear Solid, Resident Evil 2, Crash Bandicoot, Castlevania: SOTN, Spyro, Gran Turismo, Tekken 3, Silent Hill, Chrono Cross".into(),
            emulators: "RetroArch (Beetle PSX HW, PCSX ReARMed, SwanStation), DuckStation".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "ps2".into(),
            manufacturer: "Sony".into(),
            release_year: Some(2000),
            discontinue_year: Some(2013),
            generation: Some(6),
            media_type: "DVD-ROM, CD-ROM".into(),
            cpu: "Emotion Engine @ 294.912 MHz (MIPS)".into(),
            memory: "32 MB RDRAM + 4 MB VRAM".into(),
            graphics: "Graphics Synthesizer @ 147.456 MHz".into(),
            sound: "SPU2, 48 channels, Dolby Pro Logic II".into(),
            display: "480i, 480p, 1080i (rare)".into(),
            units_sold: "155+ million".into(),
            launch_price: "$299 USD".into(),
            description: "The PlayStation 2 (PS2) is a home video game console developed by Sony Computer Entertainment, released in 2000. It is the best-selling video game console of all time with over 155 million units sold worldwide. The PS2 was backward compatible with PS1 games and doubled as a DVD player, which helped drive adoption. Its library of over 4,000 titles spans every genre imaginable, including landmark franchises like Grand Theft Auto, God of War, Kingdom Hearts, and Shadow of the Colossus. Production lasted 13 years, ending in 2013.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/PlayStation_2".into(),
            image_url: String::new(),
            notable_games: "GTA: San Andreas, Shadow of the Colossus, God of War II, Kingdom Hearts, Metal Gear Solid 3, Final Fantasy X, Resident Evil 4, Persona 4, Ratchet & Clank, Devil May Cry 3".into(),
            emulators: "PCSX2, RetroArch (PCSX2)".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "ps3".into(),
            manufacturer: "Sony".into(),
            release_year: Some(2006),
            discontinue_year: Some(2017),
            generation: Some(7),
            media_type: "Blu-ray Disc, DVD".into(),
            cpu: "Cell Broadband Engine (PPE @ 3.2 GHz + 7 SPEs)".into(),
            memory: "256 MB XDR RAM + 256 MB GDDR3 VRAM".into(),
            graphics: "RSX Reality Synthesizer (NVIDIA) @ 500 MHz".into(),
            sound: "Dolby TrueHD, DTS-HD Master Audio".into(),
            display: "720p, 1080i, 1080p".into(),
            units_sold: "87.4 million".into(),
            launch_price: "$499 / $599 USD".into(),
            description: "The PlayStation 3 (PS3) is a home video game console developed by Sony Computer Entertainment, released in 2006. It featured the innovative but complex Cell Broadband Engine processor and was the first console to include a Blu-ray Disc player. Despite a rocky and expensive launch, the PS3 recovered over its lifecycle with strong exclusives and the free PlayStation Network online service. The original model was backward compatible with PS2 games. The PS3 also served as a capable media center.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/PlayStation_3".into(),
            image_url: String::new(),
            notable_games: "The Last of Us, Uncharted 2, Metal Gear Solid 4, Demon's Souls, Journey, God of War III, Gran Turismo 5, LittleBigPlanet, Red Dead Redemption, InFamous".into(),
            emulators: "RPCS3".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "psp".into(),
            manufacturer: "Sony".into(),
            release_year: Some(2004),
            discontinue_year: Some(2014),
            generation: Some(7),
            media_type: "UMD (1.8 GB), Digital".into(),
            cpu: "MIPS R4000 Allegrex @ 333 MHz".into(),
            memory: "32 MB (PSP-1000) / 64 MB (PSP-2000+)".into(),
            graphics: "GPU @ 166 MHz".into(),
            sound: "Stereo speakers, virtual 7.1".into(),
            display: "4.3\" TFT LCD, 480×272".into(),
            units_sold: "80+ million".into(),
            launch_price: "$249 USD".into(),
            description: "The PlayStation Portable (PSP) is a handheld game console developed and marketed by Sony Computer Entertainment. Released in 2004, it was the first serious competitor to Nintendo's dominance of the handheld market. The PSP featured impressive multimedia capabilities including video playback, music, and web browsing. Its UMD disc format allowed near-PS2-quality games on a portable device. The system was especially popular in Japan, hosting strong JRPG and Monster Hunter titles. Its active homebrew and modding community extended its lifespan significantly.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/PlayStation_Portable".into(),
            image_url: String::new(),
            notable_games: "Monster Hunter Freedom Unite, God of War: Chains of Olympus, Crisis Core: FF VII, Persona 3 Portable, GTA: Vice City Stories, Dissidia Final Fantasy, Patapon, LocoRoco, Daxter, Lumines".into(),
            emulators: "PPSSPP, RetroArch (PPSSPP)".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "psvita".into(),
            manufacturer: "Sony".into(),
            release_year: Some(2011),
            discontinue_year: Some(2019),
            generation: Some(8),
            media_type: "Game Card, Digital".into(),
            cpu: "ARM Cortex-A9 quad-core @ ~444 MHz".into(),
            memory: "512 MB RAM + 128 MB VRAM".into(),
            graphics: "PowerVR SGX543MP4+".into(),
            sound: "Stereo speakers".into(),
            display: "5\" OLED (orig.) / LCD (Slim), 960×544, multi-touch".into(),
            units_sold: "~15.9 million".into(),
            launch_price: "$249.99 USD".into(),
            description: "The PlayStation Vita is a handheld game console developed by Sony Interactive Entertainment, released in 2011 in Japan and 2012 elsewhere. It featured a beautiful 5-inch OLED touchscreen, dual analog sticks, rear touchpad, and dual cameras. Despite its impressive hardware, the Vita struggled commercially against mobile gaming and the Nintendo 3DS. Sony provided limited first-party support after launch, but the system thrived as an indie and JRPG platform, earning a devoted fanbase. The homebrew community has kept the system active.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/PlayStation_Vita".into(),
            image_url: String::new(),
            notable_games: "Persona 4 Golden, Uncharted: Golden Abyss, Gravity Rush, Tearaway, Soul Sacrifice, Danganronpa, Freedom Wars, Killzone: Mercenary, Ys VIII, Dragon's Crown".into(),
            emulators: "Vita3K".into(),
            updated_at: None,
        },

        // ── Microsoft ───────────────────────────────────────────
        SystemWiki {
            system_id: "xbox".into(),
            manufacturer: "Microsoft".into(),
            release_year: Some(2001),
            discontinue_year: Some(2009),
            generation: Some(6),
            media_type: "DVD-ROM".into(),
            cpu: "Intel Pentium III (Celeron) @ 733 MHz".into(),
            memory: "64 MB DDR RAM".into(),
            graphics: "NVIDIA NV2A @ 233 MHz".into(),
            sound: "NVIDIA SoundStorm (Dolby Digital 5.1)".into(),
            display: "480i, 480p, 720p, 1080i".into(),
            units_sold: "24+ million".into(),
            launch_price: "$299 USD".into(),
            description: "The Xbox is a home video game console created by Microsoft, released in 2001. It was Microsoft's first entry into the gaming console market, competing directly with the PlayStation 2 and GameCube. The Xbox featured the most powerful hardware of its generation with a built-in hard drive (a first for consoles) and an Ethernet port for Xbox Live, Microsoft's pioneering online gaming service. Halo: Combat Evolved was the system's killer app, essentially defining the console FPS genre and establishing the Xbox brand.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Xbox_(console)".into(),
            image_url: String::new(),
            notable_games: "Halo 1 & 2, Star Wars: KOTOR, Fable, Ninja Gaiden, Forza Motorsport, Jet Set Radio Future, Panzer Dragoon Orta, MechAssault, Crimson Skies, Splinter Cell".into(),
            emulators: "xemu, Cxbx-Reloaded, xqemu".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "xbox360".into(),
            manufacturer: "Microsoft".into(),
            release_year: Some(2005),
            discontinue_year: Some(2016),
            generation: Some(7),
            media_type: "DVD-DL (dual layer), Digital".into(),
            cpu: "IBM Xenon (triple-core PowerPC @ 3.2 GHz)".into(),
            memory: "512 MB GDDR3 RAM".into(),
            graphics: "ATI Xenos @ 500 MHz (unified shaders)".into(),
            sound: "320 channels, Dolby Digital 5.1".into(),
            display: "720p, 1080i, 1080p".into(),
            units_sold: "84 million".into(),
            launch_price: "$299 / $399 USD".into(),
            description: "The Xbox 360 is a home video game console developed by Microsoft, released in 2005 as the successor to the original Xbox. It was the first seventh-generation console to launch, gaining an early lead over the PlayStation 3 and Nintendo Wii. The Xbox 360 revolutionized online console gaming through Xbox Live, introduced the Achievement system, and its Xbox Live Arcade service helped popularize indie games. Despite hardware reliability issues (the 'Red Ring of Death'), the Xbox 360 was a massive commercial and cultural success, especially in North America.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Xbox_360".into(),
            image_url: String::new(),
            notable_games: "Halo 3 & Reach, Gears of War 1-3, Mass Effect 1 & 2, Red Dead Redemption, Forza 3 & 4, Alan Wake, GTA V, Dark Souls, BioShock, Fable II".into(),
            emulators: "Xenia".into(),
            updated_at: None,
        },

        // ── Atari ───────────────────────────────────────────────
        SystemWiki {
            system_id: "atari2600".into(),
            manufacturer: "Atari".into(),
            release_year: Some(1977),
            discontinue_year: Some(1992),
            generation: Some(2),
            media_type: "Cartridge".into(),
            cpu: "MOS 6507 @ 1.19 MHz".into(),
            memory: "128 bytes RAM".into(),
            graphics: "TIA, 160×192 (NTSC)".into(),
            sound: "TIA, 2 channels".into(),
            display: "NTSC/PAL RF".into(),
            units_sold: "30+ million".into(),
            launch_price: "$199 USD (1977)".into(),
            description: "The Atari 2600 (originally Atari VCS) is a home video game console released in 1977 by Atari, Inc. It is credited with popularizing the use of microprocessor-based hardware and ROM cartridges for game storage, a format that became the standard until the advent of disc-based media. The 2600 transformed the home gaming market and was a dominant force in the early 1980s, hosting iconic titles like Space Invaders and Pac-Man. The video game crash of 1983, partially attributed to oversaturated and low-quality 2600 software, eventually ended its reign.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Atari_2600".into(),
            image_url: String::new(),
            notable_games: "Space Invaders, Pitfall!, Adventure, Missile Command, Asteroids, River Raid, Pac-Man, Yars' Revenge, Frogger, Breakout".into(),
            emulators: "RetroArch (Stella), Stella".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "atari5200".into(),
            manufacturer: "Atari".into(),
            release_year: Some(1982),
            discontinue_year: Some(1984),
            generation: Some(2),
            media_type: "Cartridge".into(),
            cpu: "MOS 6502C @ 1.79 MHz".into(),
            memory: "16 KB RAM".into(),
            graphics: "ANTIC + GTIA, 320×192, 256 colors".into(),
            sound: "POKEY, 4 channels".into(),
            display: "NTSC RF".into(),
            units_sold: "~1 million".into(),
            launch_price: "$269 USD".into(),
            description: "The Atari 5200 SuperSystem is a home video game console produced by Atari, released in 1982. Internally, it was essentially an Atari 400 computer without the keyboard. It featured improved graphics over the 2600 but suffered from unreliable analog controllers and lack of backward compatibility with the hugely popular 2600 library. The system was discontinued in 1984, overshadowed by the video game crash and competition.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Atari_5200".into(),
            image_url: String::new(),
            notable_games: "Pac-Man, Centipede, Missile Command, Moon Patrol, Pole Position, Pitfall!, Star Raiders, Space Invaders".into(),
            emulators: "RetroArch (Atari800), Altirra, Atari800".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "atari7800".into(),
            manufacturer: "Atari".into(),
            release_year: Some(1986),
            discontinue_year: Some(1992),
            generation: Some(3),
            media_type: "Cartridge".into(),
            cpu: "Atari SALLY (6502C) @ 1.79 MHz".into(),
            memory: "4 KB RAM".into(),
            graphics: "MARIA, 320×240, 256 colors".into(),
            sound: "TIA (2600 compatible) + POKEY (optional)".into(),
            display: "NTSC/PAL RF".into(),
            units_sold: "~3.77 million".into(),
            launch_price: "$79.95 USD (1986 re-launch)".into(),
            description: "The Atari 7800 ProSystem is a home video game console released by Atari Corporation in 1986. Originally designed in 1984, its release was delayed due to Atari's sale and the video game crash. By the time it launched, it faced competition from the NES and Master System. Its main selling point was full backward compatibility with the Atari 2600's massive library. Its own game library received limited third-party support.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Atari_7800".into(),
            image_url: String::new(),
            notable_games: "Alien vs. Predator, Ninja Golf, Food Fight, Commando, Midnight Mutants, Choplifter!, Galaga, Ballblazer".into(),
            emulators: "RetroArch (ProSystem), A7800, BupSystem".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "atarilynx".into(),
            manufacturer: "Atari".into(),
            release_year: Some(1989),
            discontinue_year: Some(1995),
            generation: Some(4),
            media_type: "Cartridge".into(),
            cpu: "MOS 65SC02 @ 4 MHz + custom GPU/sound".into(),
            memory: "64 KB RAM".into(),
            graphics: "160×102, 4096 colors (16 on-screen)".into(),
            sound: "4 channels, stereo".into(),
            display: "3.5\" color backlit LCD".into(),
            units_sold: "~3 million".into(),
            launch_price: "$179.99 USD".into(),
            description: "The Atari Lynx is a handheld game console released by Atari Corporation in 1989. It was the world's first handheld electronic game with a color LCD display, and also featured hardware sprite scaling, rotation, and stereo sound. Despite its technical superiority over the Game Boy, the Lynx suffered from a large size, short battery life, and limited software library, resulting in poor commercial performance.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Atari_Lynx".into(),
            image_url: String::new(),
            notable_games: "California Games, Blue Lightning, Todd's Adventures in Slime World, Chip's Challenge, Warbirds, Batman Returns, Rampart".into(),
            emulators: "RetroArch (Handy, Beetle Lynx), Mednafen".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "atarijaguar".into(),
            manufacturer: "Atari".into(),
            release_year: Some(1993),
            discontinue_year: Some(1996),
            generation: Some(5),
            media_type: "Cartridge, CD-ROM (add-on)".into(),
            cpu: "Motorola 68000 @ 13.295 MHz + Tom + Jerry".into(),
            memory: "2 MB RAM".into(),
            graphics: "\"Tom\" GPU, claimed 64-bit".into(),
            sound: "\"Jerry\" DSP, 16-bit stereo".into(),
            display: "240p, 480i".into(),
            units_sold: "~250,000".into(),
            launch_price: "$249.99 USD".into(),
            description: "The Atari Jaguar is a home video game console developed by Atari Corporation, released in 1993. It was marketed as the first 64-bit gaming system (though this claim is disputed as the main CPU was a 32-bit Motorola 68000). The Jaguar was Atari's last foray into the console market. It suffered from a complex architecture difficult for developers, poor software library, and was commercially unsuccessful. Notable games include Tempest 2000, a critically acclaimed update of the arcade classic, and Alien vs. Predator.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Atari_Jaguar".into(),
            image_url: String::new(),
            notable_games: "Tempest 2000, Alien vs. Predator, Iron Soldier, Rayman, Doom, Wolfenstein 3D, Super Burnout".into(),
            emulators: "RetroArch (Virtual Jaguar), BigPEmu, Virtual Jaguar".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "atarist".into(),
            manufacturer: "Atari".into(),
            release_year: Some(1985),
            discontinue_year: Some(1993),
            generation: None,
            media_type: "Floppy Disk, Hard Drive".into(),
            cpu: "Motorola 68000 @ 8 MHz".into(),
            memory: "512 KB - 4 MB RAM".into(),
            graphics: "Shifter, 320×200 (16 colors) / 640×400 (mono)".into(),
            sound: "Yamaha YM2149 (3 ch PSG) + DMA sound (STE)".into(),
            display: "Color or monochrome monitor".into(),
            units_sold: "~6 million".into(),
            launch_price: "$799 USD (520ST)".into(),
            description: "The Atari ST is a home computer released by Atari Corporation in 1985. The 'ST' stands for 'Sixteen/Thirty-two', referencing the Motorola 68000's 16-bit external bus and 32-bit internals. The ST was popular in Europe, particularly for MIDI music production (it had built-in MIDI ports), gaming, and desktop publishing. It competed directly with the Amiga and was notable for its large library of games and productivity software.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Atari_ST".into(),
            image_url: String::new(),
            notable_games: "Dungeon Master, Populous, Speedball 2, Another World, Lemmings, Captainblood, Xenon 2, Stunt Car Racer, Oids".into(),
            emulators: "RetroArch (Hatari), Hatari, Steem SSE".into(),
            updated_at: None,
        },

        // ── NEC ─────────────────────────────────────────────────
        SystemWiki {
            system_id: "pcengine".into(),
            manufacturer: "NEC / Hudson Soft".into(),
            release_year: Some(1987),
            discontinue_year: Some(1994),
            generation: Some(4),
            media_type: "HuCard, CD-ROM".into(),
            cpu: "HuC6280 (65C02) @ 7.16 MHz".into(),
            memory: "8 KB RAM, 64 KB VRAM".into(),
            graphics: "HuC6270, 256×240, 482 colors on-screen".into(),
            sound: "HuC6280 PSG, 6 channels + CD-DA".into(),
            display: "240p".into(),
            units_sold: "~10 million".into(),
            launch_price: "¥24,800 (~$190 USD)".into(),
            description: "The PC Engine (TurboGrafx-16 in North America) is a home video game console jointly developed by NEC Home Electronics and Hudson Soft, released in 1987. It was the first console to have an optional CD-ROM add-on (the first of any console). Despite being classified as a 16-bit system, it uses an 8-bit CPU with dual 16-bit GPUs. The PC Engine was hugely successful in Japan, rivaling the Super Famicom, but struggled in North America. Its CD-ROM library features landmark titles with voiced cutscenes and CD-quality audio years before competitors.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/TurboGrafx-16".into(),
            image_url: String::new(),
            notable_games: "Bonk's Adventure, Ys I & II (CD), Castlevania: Rondo of Blood, Blazing Lazers, R-Type, Soldier Blade, Snatcher (CD), Lords of Thunder, Gate of Thunder".into(),
            emulators: "RetroArch (Beetle PCE, Beetle PCE Fast), Mednafen, Ootake".into(),
            updated_at: None,
        },

        // ── SNK ─────────────────────────────────────────────────
        SystemWiki {
            system_id: "neogeo".into(),
            manufacturer: "SNK".into(),
            release_year: Some(1990),
            discontinue_year: Some(2004),
            generation: Some(4),
            media_type: "Cartridge (AES) / MVS Arcade Board".into(),
            cpu: "Motorola 68000 @ 12 MHz + Z80 @ 4 MHz".into(),
            memory: "64 KB RAM + 68 KB VRAM".into(),
            graphics: "Custom LSPC2, 380×224, 4096 on-screen colors".into(),
            sound: "Yamaha YM2610, 15 channels".into(),
            display: "240p".into(),
            units_sold: "~1 million (AES home console)".into(),
            launch_price: "$649.99 USD (AES)".into(),
            description: "The Neo Geo is a cartridge-based arcade system board and home video game console created by SNK, released in 1990. The AES (Advanced Entertainment System) home console was identical to the MVS (Multi Video System) arcade hardware, delivering true arcade-quality gaming at home. Its extremely high price point ($649 console + $200-$600 per game) made it a luxury item. The Neo Geo is legendary for its fighting game library and remained in production for 14 years, one of the longest-lived consoles ever.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Neo_Geo_(system)".into(),
            image_url: String::new(),
            notable_games: "King of Fighters '98, Metal Slug, Garou: Mark of the Wolves, Samurai Shodown II, Last Blade 2, Blazing Star, Windjammers, Real Bout Fatal Fury, Puzzle Bobble".into(),
            emulators: "RetroArch (FinalBurn Neo, Beetle NeoPop), MAME, FBNeo".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "ngpc".into(),
            manufacturer: "SNK".into(),
            release_year: Some(1999),
            discontinue_year: Some(2001),
            generation: Some(5),
            media_type: "Cartridge".into(),
            cpu: "Toshiba TLCS-900H @ 6.144 MHz + Z80 @ 3.072 MHz".into(),
            memory: "12 KB RAM + 4 KB shared".into(),
            graphics: "152×152, 146 colors per frame".into(),
            sound: "SN76489 (3 tone, 1 noise) + DAC".into(),
            display: "2.7\" TFT color LCD".into(),
            units_sold: "~2 million".into(),
            launch_price: "$69.95 USD".into(),
            description: "The Neo Geo Pocket Color (NGPC) is a 16-bit color handheld game console manufactured by SNK, released in 1999. It is the successor to the monochrome Neo Geo Pocket. Despite excellent build quality (praised for its micro-switched joystick), a strong fighting game library, and even a link cable accessory for the Dreamcast, the NGPC had very limited commercial success against the Game Boy Color. SNK's financial troubles led to its discontinuation in 2001.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Neo_Geo_Pocket_Color".into(),
            image_url: String::new(),
            notable_games: "SNK vs. Capcom: Match of the Millennium, King of Fighters R-2, Sonic the Hedgehog Pocket Adventure, Metal Slug 1st/2nd Mission, Card Fighters Clash, Dark Arms".into(),
            emulators: "RetroArch (Beetle NeoPop), Mednafen".into(),
            updated_at: None,
        },

        // ── Other Systems ───────────────────────────────────────
        SystemWiki {
            system_id: "3do".into(),
            manufacturer: "The 3DO Company".into(),
            release_year: Some(1993),
            discontinue_year: Some(1996),
            generation: Some(5),
            media_type: "CD-ROM".into(),
            cpu: "ARM60 @ 12.5 MHz".into(),
            memory: "2 MB DRAM + 1 MB VRAM".into(),
            graphics: "Custom CEL engine, 16 million colors".into(),
            sound: "Custom DSP, 16-bit stereo, 32 channels".into(),
            display: "240p, 480i".into(),
            units_sold: "~2 million".into(),
            launch_price: "$699.99 USD".into(),
            description: "The 3DO Interactive Multiplayer is a home video game console developed by The 3DO Company and manufactured by various partners including Panasonic, LG, and Sanyo. Released in 1993, it was one of the first 32-bit consoles. Its extremely high launch price severely limited adoption despite impressive hardware for the time. The 3DO hosted a small but notable library including Road Rash, Return Fire, and several FMV games. The system's open licensing model was ahead of its time but failed commercially.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/3DO_Interactive_Multiplayer".into(),
            image_url: String::new(),
            notable_games: "Road Rash, Return Fire, Need for Speed, Star Control II, Gex, Super Street Fighter II Turbo, Wing Commander III, D, Alone in the Dark".into(),
            emulators: "RetroArch (Opera), Phoenix".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "wswan".into(),
            manufacturer: "Bandai".into(),
            release_year: Some(1999),
            discontinue_year: Some(2003),
            generation: Some(5),
            media_type: "Cartridge".into(),
            cpu: "NEC V30MZ (x86) @ 3.072 MHz".into(),
            memory: "16 KB RAM + 16 KB VRAM".into(),
            graphics: "224×144, monochrome (8 shades)".into(),
            sound: "4 channels, headphone stereo".into(),
            display: "2.49\" FSTN LCD, monochrome".into(),
            units_sold: "~3.5 million (with Color)".into(),
            launch_price: "¥4,800 (~$42 USD)".into(),
            description: "The WonderSwan is a handheld game console released by Bandai in 1999 in Japan. Designed by Gunpei Yokoi (creator of the Game Boy), it featured a unique design that could be held both vertically and horizontally. It was Japan-only and competed with the Game Boy Color. The system had strong Bandai franchise support including several Final Fantasy remakes. It was succeeded by the WonderSwan Color.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/WonderSwan".into(),
            image_url: String::new(),
            notable_games: "Final Fantasy I-III remakes, Gunpey, Digimon, Riviera, Judgement Silversword, Klonoa, Rockman EXE".into(),
            emulators: "RetroArch (Beetle Cygne), Mednafen, ares".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "wswanc".into(),
            manufacturer: "Bandai".into(),
            release_year: Some(2000),
            discontinue_year: Some(2003),
            generation: Some(5),
            media_type: "Cartridge".into(),
            cpu: "NEC V30MZ @ 3.072 MHz".into(),
            memory: "64 KB RAM".into(),
            graphics: "224×144, 241 colors (on-screen from 4096)".into(),
            sound: "4 channels + headphone output".into(),
            display: "2.8\" TFT color LCD".into(),
            units_sold: "(included in WonderSwan total)".into(),
            launch_price: "¥6,800 (~$60 USD)".into(),
            description: "The WonderSwan Color is the color successor to the WonderSwan, released by Bandai in 2000. It is backward compatible with original WonderSwan games and maintains the dual-orientation design. It was succeeded by the SwanCrystal, essentially the same hardware with a slightly improved screen. The WonderSwan Color was only released in Japan.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/WonderSwan_Color".into(),
            image_url: String::new(),
            notable_games: "Final Fantasy IV, One Piece: Grand Battle, Dicing Knight, Gundam Wing, Rhyme Rider Kerorican".into(),
            emulators: "RetroArch (Beetle Cygne), Mednafen, ares".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "colecovision".into(),
            manufacturer: "Coleco".into(),
            release_year: Some(1982),
            discontinue_year: Some(1985),
            generation: Some(2),
            media_type: "Cartridge".into(),
            cpu: "NEC 780C (Z80 clone) @ 3.58 MHz".into(),
            memory: "1 KB RAM, 16 KB VRAM".into(),
            graphics: "TMS9928A, 256×192, 16 colors".into(),
            sound: "SN76489A, 3 tone + 1 noise".into(),
            display: "NTSC/PAL RF".into(),
            units_sold: "~6 million".into(),
            launch_price: "$175 USD".into(),
            description: "The ColecoVision is a second-generation home video game console released by Coleco Industries in 1982. It offered near-arcade-quality graphics for the time, with its bundled Donkey Kong port being a major selling point. The console's hardware is closely compatible with the MSX standard and the SG-1000. An expansion module allowed it to play Atari 2600 games. The ColecoVision was discontinued in 1985 following the video game crash and Coleco's subsequent financial difficulties.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/ColecoVision".into(),
            image_url: String::new(),
            notable_games: "Donkey Kong, Zaxxon, Venture, Lady Bug, Cosmic Avenger, Smurf: Rescue in Gargamel's Castle, Pepper II, Turbo".into(),
            emulators: "RetroArch (blueMSX, Gearcoleco), ColEm, CoolCV".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "intellivision".into(),
            manufacturer: "Mattel".into(),
            release_year: Some(1979),
            discontinue_year: Some(1990),
            generation: Some(2),
            media_type: "Cartridge".into(),
            cpu: "General Instrument CP1610 @ 894.886 kHz".into(),
            memory: "1456 bytes RAM, 512 bytes SRAM".into(),
            graphics: "STIC, 159×96 (effective), 16 colors".into(),
            sound: "GI AY-3-8914, 3 channels".into(),
            display: "NTSC/PAL RF".into(),
            units_sold: "~3 million".into(),
            launch_price: "$299 USD (1980)".into(),
            description: "The Intellivision is a home video game console released by Mattel Electronics in 1979. It was the first 16-bit gaming console (though with a 10-bit instruction word) and a direct competitor to the Atari 2600. The system featured a unique controller with a 12-button numeric keypad and disc-based directional control. Intellivision marketed itself on superior graphics compared to the 2600, and its sports titles were particularly well-regarded. It survived the video game crash but was ultimately discontinued.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Intellivision".into(),
            image_url: String::new(),
            notable_games: "Astrosmash, Advanced Dungeons & Dragons, Utopia, Night Stalker, Star Strike, Tron: Deadly Discs, Bump 'n' Jump, Lock 'n' Chase".into(),
            emulators: "RetroArch (FreeIntv), jzIntv".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "msx".into(),
            manufacturer: "Microsoft/ASCII (standard)".into(),
            release_year: Some(1983),
            discontinue_year: Some(1993),
            generation: Some(3),
            media_type: "Cartridge, Floppy Disk, Cassette".into(),
            cpu: "Zilog Z80A @ 3.58 MHz".into(),
            memory: "8-64 KB RAM (varies by model)".into(),
            graphics: "TMS9918/V9938/V9958 (varies)".into(),
            sound: "AY-3-8910 (3 channels) + SCC (some games)".into(),
            display: "256×192 or 512×212 (MSX2+)".into(),
            units_sold: "~5 million".into(),
            launch_price: "Varies (multiple manufacturers)".into(),
            description: "MSX is a standardized home computer architecture established by Microsoft and ASCII Corporation in 1983. Unlike most computer standards, MSX was manufactured by multiple companies including Sony, Panasonic, Philips, and many others. The MSX standard went through several revisions (MSX, MSX2, MSX2+, MSX turbo R). It was especially popular in Japan, South Korea, South America, and parts of Europe. Konami was a major supporter, producing many classic games for the platform including Metal Gear and Castlevania.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/MSX".into(),
            image_url: String::new(),
            notable_games: "Metal Gear, Vampire Killer (Castlevania), Gradius, Space Manbow, Snatcher, Penguin Adventure, Aleste, Salamander, King's Valley II, F1 Spirit".into(),
            emulators: "RetroArch (blueMSX, fMSX), openMSX, blueMSX".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "c64".into(),
            manufacturer: "Commodore".into(),
            release_year: Some(1982),
            discontinue_year: Some(1994),
            generation: None,
            media_type: "Cartridge, Floppy Disk, Cassette".into(),
            cpu: "MOS 6510 @ 1.023 MHz (NTSC) / 0.985 MHz (PAL)".into(),
            memory: "64 KB RAM".into(),
            graphics: "VIC-II, 320×200, 16 colors".into(),
            sound: "SID 6581/8580, 3 channels (legendary chip)".into(),
            display: "NTSC/PAL composite".into(),
            units_sold: "12.5-17 million".into(),
            launch_price: "$595 USD (1982)".into(),
            description: "The Commodore 64 (C64) is an 8-bit home computer introduced in 1982 by Commodore International. It holds the Guinness World Record as the highest-selling single computer model of all time. The C64 dominated the low-end computer market for most of the 1980s, acclaimed for its affordability, the iconic SID sound chip (considered the best of its era), and a vast software library. The SID chip's distinctive sound has influenced electronic music and the demoscene to this day. The C64 was a major platform for gaming in Europe.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Commodore_64".into(),
            image_url: String::new(),
            notable_games: "Impossible Mission, Maniac Mansion, Archon, The Last Ninja, Paradroid, Elite, Bubble Bobble, International Karate+, Turrican, Wizball".into(),
            emulators: "RetroArch (VICE), VICE".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "amiga".into(),
            manufacturer: "Commodore".into(),
            release_year: Some(1985),
            discontinue_year: Some(1996),
            generation: None,
            media_type: "Floppy Disk, Hard Drive".into(),
            cpu: "Motorola 68000 @ 7.09 MHz (later models: 68020-68060)".into(),
            memory: "256 KB - 2 MB (base models)".into(),
            graphics: "Custom chipset (Agnus/Denise), 4096 colors (OCS), 16.8M (AGA)".into(),
            sound: "Paula, 4 channels, 8-bit PCM stereo".into(),
            display: "320×200 to 1280×512 (various modes)".into(),
            units_sold: "~6 million".into(),
            launch_price: "$1,295 USD (Amiga 1000, 1985)".into(),
            description: "The Amiga is a family of personal computers developed by Commodore starting in 1985. The Amiga featured custom chips (Agnus, Denise, and Paula) that provided advanced multimedia capabilities years ahead of competitors. It was a pioneer in multimedia computing, supporting advanced graphics, sound, and multitasking before these were common on PCs. The Amiga was hugely popular in Europe for gaming and creative work, and was a cornerstone of the demoscene. The platform produced many influential games and served as an early video production tool for television.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Amiga".into(),
            image_url: String::new(),
            notable_games: "Lemmings, Another World, Sensible World of Soccer, The Secret of Monkey Island, Turrican II, Speedball 2, Shadow of the Beast, Civilization, Cannon Fodder, Worms".into(),
            emulators: "RetroArch (PUAE), WinUAE, FS-UAE".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "scummvm".into(),
            manufacturer: "Various (LucasArts, Sierra, etc.)".into(),
            release_year: None,
            discontinue_year: None,
            generation: None,
            media_type: "Floppy Disk, CD-ROM, Digital".into(),
            cpu: "N/A (interpreter-based)".into(),
            memory: "N/A".into(),
            graphics: "Varies (320×200 common, up to 640×480)".into(),
            sound: "Varies (MIDI, digital audio)".into(),
            display: "Varies".into(),
            units_sold: "N/A".into(),
            launch_price: "N/A".into(),
            description: "ScummVM is a program which allows you to run certain classic graphical point-and-click adventure games, provided you already have their data files. The name 'ScummVM' comes from SCUMM (Script Creation Utility for Maniac Mansion), the game engine LucasArts developed to create most of their adventure games. ScummVM now supports a vast number of other adventure game engines from various developers including Sierra, Revolution Software, Humongous Entertainment, and many more. It is not a console but rather a compatibility layer for running classic PC adventure games on modern systems.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/ScummVM".into(),
            image_url: String::new(),
            notable_games: "The Secret of Monkey Island, Day of the Tentacle, Sam & Max, Full Throttle, Grim Fandango, King's Quest, Broken Sword, Beneath a Steel Sky, Myst, Indiana Jones and the Fate of Atlantis".into(),
            emulators: "ScummVM, RetroArch (ScummVM)".into(),
            updated_at: None,
        },

        // ── Arcade ──────────────────────────────────────────────
        SystemWiki {
            system_id: "arcade".into(),
            manufacturer: "Various (Namco, Capcom, Sega, Konami, Taito, etc.)".into(),
            release_year: Some(1971),
            discontinue_year: None,
            generation: None,
            media_type: "Arcade PCB".into(),
            cpu: "Various (Z80, 68000, ARM, x86, custom)".into(),
            memory: "Varies widely".into(),
            graphics: "Custom hardware per game/board".into(),
            sound: "Custom hardware per game/board".into(),
            display: "CRT (various resolutions)".into(),
            units_sold: "N/A (coin-operated)".into(),
            launch_price: "N/A".into(),
            description: "Arcade games are coin-operated entertainment machines found in public businesses. The golden age of arcade video games ran from 1978 to 1986, when titles like Pac-Man, Space Invaders, and Donkey Kong became cultural phenomena. Arcade hardware has varied enormously over the decades, from simple discrete logic circuits to powerful custom boards exceeding contemporary home console hardware. MAME (Multiple Arcade Machine Emulator) is the primary preservation project, cataloging and emulating thousands of arcade boards. Arcades remain popular in Japan and are seeing a global resurgence through barcades.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/Arcade_game".into(),
            image_url: String::new(),
            notable_games: "Pac-Man, Street Fighter II, Metal Slug, 1942, Galaga, Donkey Kong, Bubble Bobble, OutRun, Space Invaders, Dance Dance Revolution".into(),
            emulators: "MAME, RetroArch (MAME, FinalBurn Neo)".into(),
            updated_at: None,
        },
        SystemWiki {
            system_id: "fbneo".into(),
            manufacturer: "Various (Capcom, SNK, Cave, Sega, Konami, etc.)".into(),
            release_year: Some(1985),
            discontinue_year: None,
            generation: None,
            media_type: "Arcade PCB".into(),
            cpu: "Various (68000, Z80, ARM, SH-2, custom)".into(),
            memory: "Varies per board".into(),
            graphics: "Custom per board".into(),
            sound: "Various (YM2151, OPL3, QSound, custom)".into(),
            display: "CRT (various resolutions)".into(),
            units_sold: "N/A".into(),
            launch_price: "N/A".into(),
            description: "FinalBurn Neo (FBNeo) is an emulator focused on accurate emulation of arcade games, particularly from the late 1980s through early 2000s. It specializes in CPS-1, CPS-2, CPS-3, Neo Geo, PGM, Cave, and other popular arcade boards. FBNeo is known for its high compatibility and cycle-accurate emulation of many classic fighting games and shoot-em-ups. It supports over 7,000 games and is available both standalone and as a RetroArch core.".into(),
            wikipedia_url: "https://en.wikipedia.org/wiki/FinalBurn_Neo".into(),
            image_url: String::new(),
            notable_games: "Street Fighter II-III, King of Fighters, Metal Slug, DoDonPachi, Garou: Mark of the Wolves, Progear, Dimahoo, Mars Matrix, Strikers 1945, Puzzle Bobble".into(),
            emulators: "FinalBurn Neo, RetroArch (FinalBurn Neo)".into(),
            updated_at: None,
        },
    ]
}
